### ISSUE TITLE
REST API result always printed in log

### ISSUE THREAD

**Issue by pwnzya** [JKorf/Bittrex.Net#100]
After upgrading to the latest version 2.1.3, the logger started to always print REST API result regardless of what verbosity is set.

Code:
```
BittrexClient.SetDefaultOptions(new BittrexClientOptions()
{
     ...
     LogVerbosity = CryptoExchange.Net.Logging.LogVerbosity.None
});
var bittrexClient = new BittrexClient();
var result = bittrexClient.GetSomething();
```
Result:
     Contents of the result, which can be a very long list of data, is always printed.

Expected:
     The verbosity settings should reflect the logger output accordingly.

**Comment by JKorf** [comment]
I see, accidentally removed a check while doing some work.. Fixing it as we speak. 
Thanks for the fast report.

**Comment by JKorf** [comment]
I've pushed a new version which should fix it. Might take a few minutes for it to show up in the package manager.

**Comment by pwnzya** [comment]
Thank you for the quick fix!

Test result:

Verbosity not set (default) -> Logger doesn't print the content of the result
Verbosity set to 'Debug'    -> Logger prints the content of the result

Expected behavior confirmed.
