### ISSUE TITLE
UPDATE - Please be preparing to move to socket.bittrex.com

### ISSUE THREAD

**Issue by pwnzya** [JKorf/Bittrex.Net#101]
Bittrex team told us to start using socket.bittrex.com about 14 hours ago.
> **bittrex-pmidge**
> Heads Up: Websocket Server Status
> As promised, this is official notice that beta.bittrex.com is going be sunset, and you should move all WS API connections to socket.bittrex.com as soon as you can. The domain will remain available, so you may continue using it, but between now and Friday the resources serving it will be scaled down and I won't guarantee any kind of stability for folks continuing to connect to that resource. This change is necessary to clear the path for some other API-based work we need to do to address reported issues regarding WS stability and REST timeouts.
> 
> A note about Cloudflare: many of you have noticed Cloudflare DDOS protection has been disabled for some time, and as a general rule we will keep it off unless there is very good reason to re-enable it. As is the case in such circumstances, there will be no advance warning, and we will disable it only when we are certain it is safe to do so.

**HOWEVER**, they just posted this message...
> **bittrex-ben**
> Please hold off moving to socket.bittrex.com - the code there is outdated and will be updated soon.

> **bittrex-pmidge**
> We're going to update socket.bittrex.com as soon as we can, possibly tonight or tomorrow night. That will make sure the two bugfixes reported during beta are deployed there, somehow we missed that during post-beta wrap-up. Our end of week deadline hasn't moved, so getting changes staged on your end is still wise.
> 
> I realize for some folks this is a one-liner, but for others it is updating deployed code, pushing code to customers, etc. so I can't in good faith advise standing down.

So, we should keep using beta.bittrex.com for a few more days...

--- @JKorf ---
Sorry for the confusion.
By the way, they said that they sent you an invite to their Slack.
Please, check your email.

**Comment by pwnzya** [comment]
A new update came in today.  Important things to note are:
- once again, they told us to "be moving or preparing to move to socket.bittrex.com"
- new endpoints for "API access are **api.bittrex.com** for REST, and **socket.bittrex.com** for WS"
- the new REST endpoint **api.bittrex.com** seem available already according to a post in the Slack
- new REST v1.2 is coming (soon?), and after that they will begin working on a new generation API v3.0

Actual post by bittrex-pmidge below:
> **bittrex-pmidge**
> *Update on API Servers*: We're still working on getting the new deployment ready. Fixes for various reported websocket issues will deploy when we flip those environments over to production, and the decimal stringification fix will deploy shortly after as REST 1.2. REST 1.2 is likely the last release in the current API generation, and we will begin working on API 3.0, which is the rationalized websocket/rest release. Of course, no schedule yet available for that.
> 
> You should still be moving or preparing to move to socket.bittrex.com. Now that heads-up has been given, there will be very little warning here - maybe 30 minutes beforehand. The updated DNS domains for API access are *api.bittrex.com* for your REST and *socket.bittrex.com* for WS. When you change over *make sure you update your call signing code*.
> 
> Finally, a word on throttling. A few of you have responded privately with details of your experience, thank you. This enabled me to track down what I think is the problem behind the "I'm not making many calls so why am I being throttled" problem. I have a temporary fix in place for this, so keep an eye on your bots/apps/etc. and let me know if you think you're still seeing issues.

**Comment by JKorf** [comment]
Both rest API and socket client have been on the new endpoints for a while, considering this issue as done.
