### ISSUE TITLE
Support multiple accounts (multiple websocket connections)

### ISSUE THREAD

**Issue by sauropodlet** [JKorf/Bittrex.Net#102]
If I create two BittrexSocketClients (in a single application) for different Bittrex accounts and SubscribeToOrderUpdates on both, the second (and first) receive updates for first and no updates are received for the second.

That is, it's behaving like a singleton. If this behaviour is by design, what degree of isolation is required to make them work independently?

**Comment by sauropodlet** [comment]
Yes

**Comment by JKorf** [comment]
Currently only a single account is supported. Bittrex also has a single account policy:
https://support.bittrex.com/hc/en-us/articles/115001262712-Multiple-Account-Policy

Is there a valid reason multiple accounts should be supported?

**Comment by sauropodlet** [comment]
It looks like removing all instances of 'static' in BittrexSocketClient works.

**Comment by sauropodlet** [comment]
Keep this one

private static  BittrexSocketClientOptions defaultOptions = new BittrexSocketClientOptions();

Note: I haven't tested this beyond my needs, but would be happy to do so if you wish. I have my girlfriend's account to play with after all.

**Comment by JKorf** [comment]
The BittrexSocketClient uses static instances so that only a single websocket connection will be made to the Bittrex server, even if you use multiple BittrexSocketClients. A single websocket can only send updates for a single user though.
I'll look into changing it to support multiple accounts.

**Comment by sauropodlet** [comment]
Great, thanks.

**Comment by JKorf** [comment]
You can try the latest version (v2.1.5), it should work with multiple accounts.

**Comment by sauropodlet** [comment]
That works well for me, thanks very much.
