### ISSUE TITLE
UnobservedTaskException from QueryExchangeStateAsync call

### ISSUE THREAD

**Issue by nateonthenet** [JKorf/Bittrex.Net#106]
Using Bittrex.net 2.1.5 from NuGet, we're seeing an occasional exception from a QueryExchangeStateAsync call as follows:

```
TaskScheduler_UnobservedTaskException::System.NullReferenceException: Object reference not set to an instance of an object.
  at Bittrex.Net.BittrexSocketClient.<QueryExchangeStateAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at WSClient.<SubscribeAsync>d__13.MoveNext()
```

For context, we're subscribing to a number of symbols and calling...

```await _client.QueryExchangeStateAsync(symbol);```

...for each symbol before the actual subscription:

```
await _client.SubscribeToExchangeStateUpdatesAsync(symbol, (e) => {
[...]
});
```

This doesn't happen for every symbol, and we are able to trap it in a TaskScheduler_UnobservedTaskException handler, but obviously it would be better if it didn't happen at all.

**Comment by JKorf** [comment]
Hi, I'll look into it when I get back from holiday next week

**Comment by JKorf** [comment]
Hi, I've found the issue. Apparently the server sometimes returns "null" as a string when querying multiple markets. I added a check on this. The call will still not be successful (that's on Bittrex side) but the call result will indicate a failed call (Success = false) and no longer throw an exception.

Thanks for the report
