### ISSUE TITLE
Expose connection status of socket client

### ISSUE THREAD

**Issue by tompetko** [JKorf/Bittrex.Net#107]
It would be nice, if `BittrexSocketClient` exposes other connection status events and idications (like in SignalR's `IHubConnection`) like: Error event, last Error and State of the connection.

**Comment by JKorf** [comment]
I'll look into it when I get back from holiday next week

**Comment by JKorf** [comment]
Hi, I've added additional events in the latest version (v2.1.6), hope that helps you!
