### ISSUE TITLE
No default LogWriter

### ISSUE THREAD

**Issue by sauropodlet** [JKorf/Bittrex.Net#108]
I'm pretty sure that logging would go to console window by default until a recent update. 
In v2.1.6 LogWriters=new List<TextWriter>{Console.Out } seems to be required.

**Comment by sauropodlet** [comment]
If it wasn't done by mistake I suppose it's not an issue.

**Comment by JKorf** [comment]
This was done on purpose, console output isn't always desirable. The default uses Debug.WriteLine now which outputs in the VisualStudio debug window.
For Console logging you can/should use the options you mentioned.
