### ISSUE TITLE
Use DateTimeOffset instead of DateTime or use DateTimeKind.Utc instead of  DateTimeKind.Unspecified

### ISSUE THREAD

**Issue by sauropodlet** [JKorf/Bittrex.Net#109]
Bittrex unambiguously uses UTC for date/time in its APIs.
Bittrex.Net uses DateTime with DateTimeKind.Unspecified, which is ambiguous.

**Comment by pwnzya** [comment]
I did the following in my code to enforce UTC so that the database won't mess with the timestamps:
```
...
 for (int i = 0; i < bittrexCandles.Count(); i++)
 {
     bittrexCandles[i].Timestamp = bittrexCandles[i].Timestamp.ToLocalTime().ToUniversalTime();
 }
...
```

**Comment by JKorf** [comment]
I pushed a new version in which all DateTime objects should have the Kind set to Utc.
The kind isn't set correctly to Utc by default because the data the Bittrex server returns actually doesn't specify that it is Utc explicitly even though it is.
