### ISSUE TITLE
This isn't a Issue, is a Doubt: in PlaceOrder!

### ISSUE THREAD

**Issue by ffranzes** [JKorf/Bittrex.Net#110]
Hi, what rate means in a placeorder ? and how we place a limitsell or limitbuy order? and stoploss ?
PlaceOrderAsync(Bittrex.Net.Objects.OrderSideExtended.LimitSell, Pair, qntt, ? ) is that right?
Thank you!

**Comment by JKorf** [comment]
Hi, the rate is the price of the order. Say you want to buy 2 ETH with BTC at 0.5btc each you would to the following:
`PlaceOrderAsync(OrderType.Buy, "BTC-ETH", 2, 0.5m)`
Note that the OrderSideExtended enum isn't valid input for this method, that one is only used for parsing results gotten from the server. 

You can use `PlaceConditionalOrder` to place stop loss orders.
