### ISSUE TITLE
Cancel Order always returns INVALID_ORDER

### ISSUE THREAD

**Issue by mclean25** [JKorf/Bittrex.Net#111]
I'm not sure if this is a problem with this repository or Bittrex's back-end (or my code maybe) but I keep getting an INVALID_ORDER error when calling `Client.CancelOrder(Guid)`. Is anyone else getting this issue?

**Comment by JKorf** [comment]
Have you resolved this issue or closed it on accident?

**Comment by mclean25** [comment]
Hi @JKorf , I did a bunch more testing and created #112 

thanks
