### ISSUE TITLE
REST Authentication Failing

### ISSUE THREAD

**Issue by pwnzya** [JKorf/Bittrex.Net#114]
After updating Bittrex.Net to v2.1.12 and CryptoExchange.Net to v0.0.38, REST authentication stopped working for me.  

Error message = "Server error: APIKEY_INVALID"

CODE:
```
BittrexClient.SetDefaultOptions(new BittrexClientOptions(){
   ApiCredentials = new ApiCredentials(<apiKey>, <secret>)
});
var bittrexClient = new BittrexClient();
var response = await bittrexClient.GetBalancesAsync();
```
I also tried
```
var bittrexClient = new BittrexClient();
bittrexClient.SetApiCredentials(<apiKey>, <secret>);
var response = await bittrexClient.GetBalancesAsync();
```
but no luck.

Finally, I tried a new set of keys but no luck there either.

EDIT: Websocket authentication is working, and I can subscribe to account balance stream.

EDIT2: 
  Bittrex.Net v2.1.11 and CryptoExchange.Net v0.0.37 didn't work either, but 
  Bittrex.Net v2.1.10 and CryptoExchange.Net v0.0.31 works.

**Comment by JKorf** [comment]
Hi, you're right. Small oversight while doing some work on a new library and updating CryptoExchange.Net. It should be fixed in v2.1.13 which I just pushed.
Thanks for the report!
