### ISSUE TITLE
 Could not install package 'Bittrex.Net 2.1.16'

### ISSUE THREAD

**Issue by qpile** [JKorf/Bittrex.Net#116]
Hello!
I have got this error during instalation via Nuget
Install failed. Rolling back...
Package 'Bittrex.Net.2.1.16' does not exist in project 'Bittrex'
Package 'Bittrex.Net.2.1.16' does not exist in folder 'D:\Application\Crypto\Bittrex\Bittrex\packages'
Install-Package : Could not install package 'Bittrex.Net 2.1.16'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references 
or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Bittrex.Net
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM>

**Comment by JKorf** [comment]
Hi, the package targets .NetStandard2.0, which needs at least .Net framework 4.6.1. You're trying to install it in 4.5.2 which sadly isn't compatible.

**Comment by qpile** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Bittrex.Net 2.1.16'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by qpile** [comment]
The same problem

**Comment by qpile** [comment]
I am using WPF project

**Comment by JKorf** [comment]
Make sure your visual studio is up to date. If you're using 2015 you'll also need to update the nuget client. You can download it from here: https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix

**Comment by qpile** [comment]
THank you! it also required to install .NetStandart2.0
Now it works perfectly!
