### ISSUE TITLE
Getting current highest bid and lowest ask through web sockets

### ISSUE THREAD

**Issue by robinabganpat** [JKorf/Bittrex.Net#118]
Is it currently possible to retrieve the highest bid and lowest ask offer, allong with the current amount for that price for a specific/all markets? If so, how could this be achieved?

I know SubscribeToExchangeStateUpdates returns the orders placed, but does not always return the best bid and ask prices with the amounts.
SubscribeToMarketSummariesUpdate returns the highest bid and lowest ask, but does not show how much the current total of those is.

Is it possible to retrieve best of both worlds?

**Comment by JKorf** [comment]
Hi, this is not something the API provides. The only way to do this is to keep track of the order book yourself, by querying the exchange state and subscribing to updates. Though that would be hard to do for all markets.

**Comment by robinabganpat** [comment]
Ah allright. Thank you for the response. Is the Bid and Ask given in the socket SubscribeToMarketSummariesUpdate method always the highest bid and lowest ask?

**Comment by JKorf** [comment]
It should be, however the websocket has a certain update interval which means that in the time between the updates it might not be accurate anymore.. That's a limitation of the Bittrex API though.

**Comment by robinabganpat** [comment]
Allright, thank you. I'm now subscribing on the order books per market to maintain the order book myself.
I ran into a different issue when running my appliccation for a while. I saw the Process Memory usage grow over time. When profiling what caused the increase I saw the following:
![image](https://user-images.githubusercontent.com/22347818/44874253-dbf4e180-ac9a-11e8-9ba7-f14f989d58f4.png)

There are a few Newtonsoft.Json related object types which grow larger over time. I suspect this is the cause of requesting the API and serializing/deserializing the requests and/or responses.

Do you know or have you experienced such increase also?
I'm using the BittrexSocketClient.SubscribeToExchangeStateUpdatesAsync() method for exhange updates.
