### ISSUE TITLE
SubscribeToMarketSummariesUpdate issue

### ISSUE THREAD

**Issue by avechuche** [JKorf/Bittrex.Net#120]
Hello, I am trying to subscribe to a particular market, but "SubscribeToMarketSummariesUpdate" does not accept 2 parameters, what is the problem? Thank you!

```
var socketClient = new BittrexSocketClient();
var subcribtionSuccess = socketClient.SubscribeToMarketSummariesUpdate("BTC-ETH", data =>
{
	// Handle data
});
```

**Comment by JKorf** [comment]
Hi, I see the ReadMe is a little outdated. The `SubscribeToMarketSummariesUpdate` method doesn't take a market name, only a handler. So you receive updated states for every market that has changed since the last update. If you want the info for a specific market just filter the data list.
