### ISSUE TITLE
Not receiving all BittrexStreamUpdateExchangeStates

### ISSUE THREAD

**Issue by robinabganpat** [JKorf/Bittrex.Net#121]
I'm currently subscribing to all markets on Bittrex (around 280) using the SubscribeToExchangeStateUpdatesAsync() method, using 10 BittrexSocketClient instances using different key pairs. The given updates comes with a nonce which I use to make sure all updates are handled in the correct order.
The problem is that I sometimes don't receive the update for a nonce. For example: I get nonce 923, 924, 926, but never get the update with nonce 925. Could this be due to the fact that I'm subscribed to too many markets? If so, could anyone explain how such behaviour could be the result (I'd suspect it to just be slower, not handling an update at all). Hope to hear what you think!

**Comment by JKorf** [comment]
Hi, that's a lot of information to process. I agree with you, I would expect the data to be lacking behind when you're not processing fast enough, not just skip over stuff. I couldn't reproduce the problem with only a few markets, could you try to see if you still see this when processing less data?

**Comment by robinabganpat** [comment]
Processing less data/subscribing to less markets fixed the issue for me.
