### ISSUE TITLE
Can't see a socket to subscribe to 'trades' data

### ISSUE THREAD

**Issue by HollandRisley** [JKorf/Bittrex.Net#123]
Hi, thanks for this excellent library. Your work is very much appreciated here.

I am trying to subscribe to a socket to get latest 'trades' data. i.e. completed buys and sells data to populate the tape. 

I've tried subscribing to each of the streams but I can't see a socket for getting that data. Am I missing something? Can you kindly point me in the right direction?

**Comment by JKorf** [comment]
Hi, you're right, there is no subscription for that data. Sadly, that's because the API doesn't offer an endpoint for that: https://bittrex.github.io/

**Comment by HollandRisley** [comment]
Oh! OK, thanks. I wonder how Coinigy gets their trade data from Bittrex?

**Comment by HollandRisley** [comment]
Ah I see, I can access the market History through the `client.GetMarketHistory` method! Thanks again!
