### ISSUE TITLE
V2 API methods broken

### ISSUE THREAD

**Issue by sauropodlet** [JKorf/Bittrex.Net#125]
I'm getting a 404 on GetCandles but other calls (e.g. GetMarketSummary) are working
v 2.1.16

**Comment by JKorf** [comment]
Hi, you're right. Bittrex updated their API and moved this call. The candles endpoint can pretty easily be fixed, it's just a different address, but the Conditional order endpoint also is changed/broken. I'm looking into that as well.

**Comment by sauropodlet** [comment]
Thanks @JKorf .

**Comment by robinabganpat** [comment]
I am receiving an HTML error message as response using the conditional order from the API. I don't know whether it has to do with the V2 API updates. Here's the response (I've omitted most of the HTML boilerplate):
`<div class="error">&nbsp;</div>
<div class="blurb-text">
   <h3>500 - Something went wrong on our end!</h3>
   <div>
      Don't worry &mdash; it's not you, it's us. You can click the <a href="javascript:history.back()">back</a> button in your browser,
      or try heading over to the Bittrex <a href="/Home/Markets">homepage</a> and explore our markets.
      <br /><br />
      Please contact <a href="http://bittrex.com/Home/Contact">Bittrex Support</a> if you have any questions or concerns.
   </div>
</div>`

**Comment by JKorf** [comment]
You're right, the PlaceConditionalOrders method still isn't working. I'm in contact with Bittrex, however since it isn't an official API method (It's just a method used by the website, not part of the API documentation) I might not be able to fix it. Still looking into it though. Created a separate issue for this #126.
