### ISSUE TITLE
Market MinTradeSize VS DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT

### ISSUE THREAD

**Issue by robinabganpat** [JKorf/Bittrex.Net#127]
All markets come with a MinTradeSize. I just experienced a sell order where the MinTradeSize requirement was met, but I received the DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT error on executing the order. 

Do any of you have any idea how I should interpret the MinTradeSize? It would suck if I would have to convert every order to their BTC value in order to be sure I won't receive the DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT error.

**Comment by sauropodlet** [comment]
Bittrex is expressing the minimum trade size in BTC only, whatever currency pair you are trading, so the conversion is unavoidable.

**Comment by JKorf** [comment]
Hi, I asked this on the Bittrex slack and they say it's intended. So I'm afraid you'll have to check whether or not its below 50k sats.

**Comment by robinabganpat** [comment]
Thanks for your responses. Any idea what price to take for the 50k sats comparison? Lowest ask when buying and highest bid when buying? Price differences will be minimal, but I want to prevent hitting that DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT error again.
