### ISSUE TITLE
why in double and not decimal.

### ISSUE THREAD

**Issue by Cjay93** [JKorf/Bittrex.Net#13]
since you have all the formats in double some numbers get displayed as 4.695E-05.
Also about the websocket, it seems rather slow on asks and bids.
how often is it updating.
Thanks love the work.

**Comment by JKorf** [comment]
Hi, all doubles have been changed to decimals in commit fbc3dece4961336c8ae96102b2c20b063fa474d5, so if you grab the latest version you should be okay. 

Regarding the websocket, I think currently the websocket sends updates every +- 10 seconds. Sadly this is not something I can change, it's just how often Bittrex provides a data update.
