### ISSUE TITLE
How to call SubscribeToAccountUpdates

### ISSUE THREAD

**Issue by GonzoKK** [JKorf/Bittrex.Net#130]
I'm struggling to implement the syntax for SubscribeToAccountUpdates. 

I can get Order Updates using...

 myBittrexSocketClient.SubscribeToAccountUpdates(null, data => {
       BittrexStreamOrderData bittrexStreamOrderData = data;
       etc

How do i also get Balance Updates?

**Comment by GonzoKK** [comment]
i think I have found the syntax problem, gonna test later

**Comment by NyScorpy** [comment]
Did you figure it out? If so, could you please share a code snipped, because i have the same Problem.

**Comment by GonzoKK** [comment]
let me know if this helps...
`
var subscriptionResult = await myBittrexSocketClient.SubscribeToAccountUpdatesAsync(
   
     data => {//BALANCE UPDATE
        if(data != null) {
            BittrexStreamBalance streamBalance = data.Delta;
            //etc 
        }//if
    },//data1 BALANCE UPDATE 
    
    data => {//ORDER UPDATE
        if(data != null) {
            BittrexStreamOrderData streamOrderData = data;
            //etc 
        }//if
    }//data2 ORDER UPDATE
);
`

**Comment by NyScorpy** [comment]
Yes it work's, thank for the fast repy!!

**Comment by ewrdietsch** [comment]
How does SubscribeToAccountUpdatesAsync work, I have not yet been able to put it to work, how do I get the data that it returns? and what type of data does it return if it is a list or what type?

**Comment by JKorf** [comment]
Hi, next time please open a new issue instead of reviving old ones.

Here's an example of a simple console application which subscribes to account updates:
````C#
    class Program
    {
        static void Main(string[] args)
        {
            var credentials = new ApiCredentials("Key", "Secret");
            var socketOptions = new BittrexSocketClientOptions()
            {
                LogVerbosity = LogVerbosity.Debug,
                ApiCredentials = credentials
            };

            var client = new BittrexSocketClient(socketOptions);
            var subscribeResult = client.SubscribeToAccountUpdates(OnBalanceUpdate, OnOrderUpdate);
            if (!subscribeResult.Success)
            {
                Console.WriteLine($"Failed to subscribe: {subscribeResult.Error}");
                Console.ReadLine();
            }

            Console.WriteLine("Listening..");
            Console.ReadLine();
        }

        private static void OnBalanceUpdate(BittrexStreamBalanceData balanceData)
        {
            // Handle the balance data, for now just write some info
            Console.WriteLine($"Received a balance update, new balance: {balanceData.Delta.Balance} {balanceData.Delta.Currency}");
        }
        
        private static void OnOrderUpdate(BittrexStreamOrderData orderData)
        {
            // Handle the order data, for now just write some info
            Console.WriteLine($"Received an order update: {orderData.Type}, remaining quantity: {orderData.Order.QuantityRemaining}");
        }
    }
````

You can test it by running this and after it writes 'listening..' open a new order on Bittrex. It will write the lines specified in the callback.
