### ISSUE TITLE
InvalidCastException when I've tryed to use newest version of library

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bittrex.Net#131]
System.InvalidCastException: 'Unable to cast object of type 'CryptoExchange.Net.Sockets.BaseSocket' to type 'Bittrex.Net.Interfaces.ISignalRSocket'.'
when I call socketApi.SubscribeToMarketSummariesUpdate(OnUpdateSummaries)

**Comment by JKorf** [comment]
Hi, this issue is currently being resolved, new version should be available in a few minutes

**Comment by JKorf** [comment]
Should be fixed in the latest version
