### ISSUE TITLE
websock

### ISSUE THREAD

**Issue by muteddisk** [JKorf/Bittrex.Net#132]
Hi,
I have this error no matter what websock call is being made

![image](https://user-images.githubusercontent.com/30062459/49613371-70936d80-f975-11e8-8dc0-107b1244d00f.png)

**Comment by JKorf** [comment]
That one should be fixed in the latest version (I released some patches after the initial new version releases as the roll out was a little less smooth than i'd hoped ;))

**Comment by muteddisk** [comment]
It's fine with me. You are doing amazing work.

Thanks for everything again!
