### ISSUE TITLE
PlaceConditionalOrderAsync on Linux gives an INVALID_SIGNATURE

### ISSUE THREAD

**Issue by loodakrawa** [JKorf/Bittrex.Net#134]
Hi,

BittrexClient.PlaceConditionalOrderAsync is returning a "Server error: INVALID_SIGNATURE" when run on Linux (CentOS 7.5 x64). The same code (with the same key and secret) works fine on Windows. 

Additionally, BittrexClient.GetBalancesAsync() and BittrexClient.GetBalanceAsync() work fine on both platforms.

**Comment by loodakrawa** [comment]
I've done a lot of tests and it seems that the issue is not OS related but rather location related. Running the code outside the US works fine with the `https://international.bittrex.com` base address but it fails when run inside the US. And the opposite is true for `https://bittrex.com` - works fine in US and doesn't work outside. The problem happens because the whole url is included in the signature process and not just the path+query.

**Comment by loodakrawa** [comment]
I've done a lot of tests and it seems that the issue is not OS related but rather location related. Running the code outside the US works fine with the `https://international.bittrex.com` base address but it fails when run inside the US. And the opposite is true for `https://bittrex.com` - works fine in US and doesn't work outside. The problem happens because the whole url is included in the signature process and not just the path+query.

**Comment by JKorf** [comment]
Since conditional orders are no longer supported and we'll have to wait for the V3 API I'm closing this.
