### ISSUE TITLE
SignalR client interlocks the subscription calls

### ISSUE THREAD

**Issue by daerhiel** [JKorf/Bittrex.Net#135]
Hi J, I'm looking at SignalR SubscribeTo* methods behavior and when invoke these methods from parallel threads, they go sequentially, like there's a lock inside the client to allow only one call being active at a time. But it seems it's not the case as there's no locks on hub proxy invocation. But what I found is that you use just a single proxy per client, and this prevents 'Invoke' method from being called in parallel.

As far as I know, hubs should be instantiated on 'per request' basis, when it's needed. Could you try to either create hubs when the invocation or subscription is needed or rely on DI for this? SignalR should either have its own DI mechanism or rely on the net.core DI support.

The reason why I'm asking, is when you have multiple subscriptions, the connection phase takeas unreasonable long time, and I think that can be fixed.

Andrey.

**Comment by JKorf** [comment]
You're right in that it takes too long to (re)connect when having a lot of subscriptions. However I'm not sure how to fix it since it's something in the SignalR client which apparently can't make parallel connections at the same time.

If you have any suggestions on how to do anything about this I'd love to hear it.

Meanwhile I'm probably going to wait for v3 of the Bittrex API, which is no longer dependent on SignalR and is currently in private beta testing.

**Comment by daerhiel** [comment]
I can make pull request and fix it.

**Comment by JKorf** [comment]
Sure, I'd be happy to see how to solve it

**Comment by daerhiel** [comment]
Well... I was too arrogant to think that I could easily fix that, I'm sorry :D.. Hub clients are really the sequential clients, and I also didn't pay attention to that fact that you're using asp.net 2.0 signalr client, not the asp.net core one..

Well, it's just a sporting interest now, I'm trying to debug the couple Bittrex.Net 3 -> SignalR 2 locally and find the interlocking points, will wee what I get out of it..

**Comment by JKorf** [comment]
Haha that's okay. I vaguely remember not being able to use the .net core one, but can't recall the reason. It was a while back and the .net core one didn't support something I needed at that time I think.

Let me know if you find something, I'm interested :)
