### ISSUE TITLE
Working with winforms

### ISSUE THREAD

**Issue by TomdeWinter** [JKorf/Bittrex.Net#14]
Hi,

Is there a sdk to guide me using this in a winform project?
Can't seem to get it working there.

Many thanks,

Tom

**Comment by JKorf** [comment]
Hi,

I'm not sure what you mean by sdk, but the Wiki explains how to use the project. I've added a small winforms example project to the Examples folder, hope that helps you get going. If you need additional help let me know.

**Comment by TomdeWinter** [comment]
Hello JKorf,

Wow, that's what I call responsive, awesome and thanks for the sample.
With sdk I meant an software development kit :-) and I was hoping for a simple example of the 
"var price = client.GetTicker("BTC-ETH");"for instance so I could easily convert it to vb.net which I use.

thanks and cheers!

Tom

**Comment by JKorf** [comment]
Can I assume you have enough information now? I know the example is in C# and the call it does is a slightly different one but the idea is the same and converting it into VB shouldn't be hard.

**Comment by cooljbg** [comment]
Would you add subscribe to all markets instead subscribing to them in foreach?
Something like:
bool subscribeToall = false;
private Action<BittrexMarketSummary> onUpdateAll;


public async Task<BittrexApiResult<int>> SubscribeToAllMarketDeltaStream(Action<BittrexMarketSummary> onUpdate){
  subscribeToAllSummaries = true;
 onUpdateAll = onUpdate;
...........
}

private void SocketMessage(IList<JToken> jsonData){
if (subscribeToAllSummaries) {
                    foreach (var delta in data.Deltas)
                        onUpdateAll(delta);
                }
                else
                {
                    foreach (var delta in data.Deltas)
                        foreach (var update in registrations.Where(r => r.MarketName == delta.MarketName))
                            update.Callback(delta);
                }
}

**Comment by TomdeWinter** [comment]
Yes, thank you. I am somewhat fighting the asynchronous programming but i am getting my head around it  more and more.

I was wondering why i couldnt use "var price = client.GetTicker("BTC-ETH");" on a button_click event but it has to be a Task.Run call.

Thanks again.

**Comment by JKorf** [comment]
Good to hear, good luck with your learning :)
