### ISSUE TITLE
BittrexClient.GetBalances() returning null for some fields of some markets

### ISSUE THREAD

**Issue by ElevenBillionCactusPincushionIdeas** [JKorf/Bittrex.Net#141]
BittrexClient.GetBalances() returning null for some fields of some markets. Presumably related to last night's bittrex.com changes.

**Comment by JKorf** [comment]
Yup, seems like Bittrex changed some logic on that. Can't do much about that on this end.

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
OK. I'll check for nulls on my end. Thanks.

**Comment by FreekPaans** [comment]
We hit this issue as well, only for `BittrexAccountOrder`. We get deserialization errors on the `Reserved` field because it is `null` in the Bittrex response.

I think it can be fixed on the Bittrex.Net end by making those fields nullable.

**Comment by JKorf** [comment]
Is it only the reserved field which is now apparently a nullable?

**Comment by FreekPaans** [comment]
Not sure, it's the only one that hit us. We fixed by cloning the repo and removing all the fields we don't require.
What's also more interesting is that the docs https://bittrex.github.io/api/v1-1#operation--account-getorder-get don't even mention this field.

**Comment by JKorf** [comment]
The documentation isn't always updated, they're busy working on V3 of the API which is currently in closed alpha. I currently don't have funds on Bittrex, could you maybe check the response data using LogVerbosity.Debug and check the json data to see if any more of the fields are null?

**Comment by FreekPaans** [comment]
I'm sorry, I don't have time to look into this now. Maybe next week.

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
I think all zero balances (Pending, Balance, Available) are null.

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
GetOrderHistory() is failing:

Error deserializing data: Deserialize JsonSerializationException: Error setting value to 'Condition' on 'Bittrex.Net.Objects.BittrexOrderHistoryOrder'

**Comment by danielbroy** [comment]
Here is a sample of the response data Bittrex sends since the API update:

{
  "success": true,
  "message": "",
  "result": {
    "AccountId": null,
    "OrderUuid": "a154345b-33d4-4e78-a5c0-1899b6387e7b",
    "Exchange": "BTC-RDD",
    "Type": "LIMIT_SELL",
    "Quantity": 21367.21260766,
    "QuantityRemaining": 0.0,
    "Limit": 3.1E-07,
    "Reserved": null,
    "ReserveRemaining": null,
    "CommissionReserved": null,
    "CommissionReserveRemaining": null,
    "CommissionPaid": 1.655E-05,
    "Price": 0.00662383,
    "PricePerUnit": 3.1E-07,
    "Opened": "2019-03-01T09:26:13.65",
    "Closed": "2019-03-01T09:26:13.65",
    "IsOpen": false,
    "Sentinel": null,
    "CancelInitiated": false,
    "ImmediateOrCancel": false,
    "IsConditional": false,
    "Condition": "",
    "ConditionTarget": 0.0
  }
}

To get this working I has to make the fields Reserved, ReserveRemaining, CommissionReserved, CommissionReserveRemaining and Sentinel nullable and convert Condition to a string. I don't no if there are use cases in which other fields might be returned as null as well.

HTH

**Comment by JKorf** [comment]
Hi, 
Thanks for the data @danielbroy.
I've pushed an update (v3.0.6) in which the fields are nullable. Let me know if that fixes everything.

**Comment by danielbroy** [comment]
@JKorf Hi there,

Thanks, I'll test. Quick check: did you see that the condition field can still sometimes have the value "NONE"? The value "" for this field is an additional possible return value, not a replacement of the none option "NONE".

**Comment by JKorf** [comment]
Hm no I didn't. Why would they have both None and empty? Do you know what the difference is?

**Comment by danielbroy** [comment]
No idea, sorry. I only know that I've seen both values returned.

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
GetOpenOrders(), 3.0.6 is giving me this:

Error deserializing data: Deserialize JsonSerializationException: Error setting value to 'Condition' on 'Bittrex.Net.Objects.BittrexOpenOrdersOrder'.. Received data: {
  "success": true,
  "message": "",
  "result": [
    {
      "Uuid": null,
      "OrderUuid": "redacted",
      "Exchange": "BTC-ZIL",
      "OrderType": "LIMIT_SELL",
      "Quantity": 11125.4255678,
      "QuantityRemaining": 11125.4255678,
      "Limit": 8E-06,
      "CommissionPaid": 0.0,
      "Price": 0.0,
      "PricePerUnit": null,
      "Opened": "2019-02-27T23:16:57.96",
      "Closed": null,
      "CancelInitiated": false,
      "ImmediateOrCancel": false,
      "IsConditional": false,
      "Condition": "NONE",
      "ConditionTarget": null
    },
    {
      "Uuid": null,
      "OrderUuid": "redacted",
      "Exchange": "BTC-XHV",
      "OrderType": "LIMIT_SELL",
      "Quantity": 498.87820998,
      "QuantityRemaining": 498.87820998,
      "Limit": 0.00012445,
      "CommissionPaid": 0.0,
      "Price": 0.0,
      "PricePerUnit": null,
      "Opened": "2019-02-27T23:16:57.96",
      "Closed": null,
      "CancelInitiated": false,
      "ImmediateOrCancel": false,
      "IsConditional": false,
      "Condition": "NONE",
      "ConditionTarget": null
    },
    {
      "Uuid": null,
      "OrderUuid": "redacted",
      "Exchange": "BTC-WINGS",
      "OrderType": "LIMIT_SELL",
      "Quantity": 1885.94822856,
      "QuantityRemaining": 1885.94822856,
      "Limit": 2.193E-05,
      "CommissionPaid": 0.0,
      "Price": 0.0,
      "PricePerUnit": null,
      "Opened": "2019-02-27T23:16:57.94",
      "Closed": null,
      "CancelInitiated": false,
      "ImmediateOrCancel": false,
      "IsConditional": false,
      "Condition": "NONE",
      "ConditionTarget": null
    },
    {
      "Uuid": null,
      "OrderUuid": "redacted",
      "Exchange": "BTC-WINGS",
      "OrderType": "LIMIT_SELL",
      "Quantity": 910.99499214,
      "QuantityRemaining": 910.99499214,
      "Limit": 2.251E-05,
      "CommissionPaid": 0.0,
      "Price": 0.0,
      "PricePerUnit": null,
      "Opened": "2019-02-27T23:16:57.94",
      "Closed": null,
      "CancelInitiated": false,
      "ImmediateOrCancel": false,
      "IsConditional": false,
      "Condition": "NONE",
      "ConditionTarget": null
    },
[continues]

**Comment by Dyou** [comment]
same error here, i guess it's just that one change you made in Bittrex.Net/Converters/ConditionTypeConverter.cs

{ ConditionType.None, "NONE" },
 was changed to           { ConditionType.None, "" },

**Comment by JKorf** [comment]
Sorry for the wait guys, I've been sick. I've pushed a new version which should work with both `"Condition": "NONE"` and `"Condition": ""`.

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
I hope you are feeling much better. Thanks very much for the fix.

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
GetMarketSummariesAsync fails during deserialization if Bid or Ask is null.
This happened today when BTC-CRO went live.

    {
      "MarketName": "BTC-CRO",
      "High": null,
      "Low": null,
      "Volume": null,
      "Last": null,
      "BaseVolume": null,
      "TimeStamp": "2019-03-07T19:01:51.0681391+00:00",
      "Bid": null,
      "Ask": null,
      "OpenBuyOrders": null,
      "OpenSellOrders": null,
      "PrevDay": null,
      "Created": "2019-03-07T19:01:45.273"
    },

**Comment by JKorf** [comment]
That's unfortunate, I'll fix it tomorrow. Thanks for the info

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
Your work is appreciated

**Comment by JKorf** [comment]
Just pushed version 3.0.8, should be available in a few minutes.
