### ISSUE TITLE
BittrexClient.GetBalances() broken if latest version used with latest CryptoExchange.net

### ISSUE THREAD

**Issue by ElevenBillionCactusPincushionIdeas** [JKorf/Bittrex.Net#142]
BittrexClient.GetBalances() broken if latest Bittrex.Net used with latest CryptoExchange.Net.
CryptoExchange.net 2.0.10 is compatible.

**Comment by JKorf** [comment]
Hi, could you elaborate on what's broken? It works for me locally.

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
Versions as above, GetBalances() gives:

Method not found: 'System.Threading.Tasks.Task`1<CryptoExchange.Net.Objects.CallResult`1<!!0>> CryptoExchange.Net.RestClient.ExecuteRequest(System.Uri, System.String, System.Collections.Generic.Dictionary`2<System.String,System.Object>, Boolean, Boolean)'.

Similar error for GetOpenOrders()

**Comment by JKorf** [comment]
It seems like it is searching for the old version of the `ExecuteRequest` which is no longer available in the 2.0.11 version. Could you try to clean and rebuild the solution?

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
Visual Studio had problems. Sorry to bother you.
