### ISSUE TITLE
LINQ InvalidOperationException on QueryExchangeStateAsync

### ISSUE THREAD

**Issue by daerhiel** [JKorf/Bittrex.Net#143]
Hi J, I have encountered a problem today when calling ``QueryExchangeStateAsync`` method on SignalR client. It throws the LINQ exception when enumerating sockets: 'Sequence contains more than one matching element'. It happens intermittently, so I can't say what conditions are needed to reproduce it.

Below is the stack trace.
``   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at CryptoExchange.Net.SocketClient.GetBackgroundSocket(Boolean authenticated)
   at Bittrex.Net.BittrexSocketClient.Query[T](ConnectionRequest request)
   at Bittrex.Net.BittrexSocketClient.QueryExchangeStateAsync(String marketName)
... (External Code)``

**Comment by JKorf** [comment]
Hi, I've found this issue, should be fixed in the latest version

**Comment by JKorf** [comment]
Assuming this is fixed
