### ISSUE TITLE
Place Conditionnal Order fail : code 3

### ISSUE THREAD

**Issue by Trapoh** [JKorf/Bittrex.Net#144]
Hello,

Seems that Bittrex changed its API to v3 which isn't available to everyone for now, and the v2 is broken, all we can do is waiting i guess...

**Comment by JKorf** [comment]
I've asked about this on the Slack channel, but I fear we might have lost conditional order placement until v3 is released. PlaceConditionalOrder was part of the V2 api which was never officially supported by Bittrex.

**Comment by JKorf** [comment]
Update:
![image](https://user-images.githubusercontent.com/8448172/53980161-ec858900-410f-11e9-9286-a350b9adfdd0.png)

**Comment by JKorf** [comment]
I'll close this as it doesn't look like this will be supported for now. I'll add it back in when Bittrex API will offer it again.
