### ISSUE TITLE
SubscribeToAccountUpdates/onOrderUpdate deserialization error

### ISSUE THREAD

**Issue by ElevenBillionCactusPincushionIdeas** [JKorf/Bittrex.Net#145]
Error deserializing data: Deserialize JsonSerializationException: Error setting value to 'Condition' on 'Bittrex.Net.Objects.BittrexStreamOrder'.. Received data: {
  "N": 74,
  "TY": 0,
  "o": {
    "E": "BTC-MUE",
    "OT": "LIMIT_BUY",
    "Q": 2577.31958762,
    "q": 2577.31958762,
    "X": 3E-06,
    "n": 0.0,
    "P": 0.0,
    "PU": 0.0,
    "C": null,
    "i": true,
    "CI": false,
    "K": false,
    "k": false,
    "J": null,
    "j": null,
    "PassthroughUuid": null
  }
}

(IDs removed)

**Comment by JKorf** [comment]
Thats nice, in the websocket the condition is null.. So it's either an empty string, NONE or null. 
I'll fix it somewhere today

**Comment by JKorf** [comment]
Fix is pushed, should be available in a few minutes

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
All good. Many thanks.
