### ISSUE TITLE
GetOrderHistory deserialization fails if OrderType = MARKET_BUY

### ISSUE THREAD

**Issue by ElevenBillionCactusPincushionIdeas** [JKorf/Bittrex.Net#148]
GetOrderHistory requests fail if OrderType = MARKET_BUY

**Comment by JKorf** [comment]
Hi, thanks for the report. I've fixed it in the latest release.

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
That's fixed, thanks very much. 

Unfortunately Limit is null on the same order, so that's another failure. Sorry I should have posted the json earlier.

The strange looking order is the result of participation in the recent Ocean IEO.

     "OrderUuid": "some_id",
      "Exchange": "BTC-OCEAN",
      "TimeStamp": "2019-04-30T18:59:15.47",
      "OrderType": "MARKET_BUY",
      "Limit": null,
      "Quantity": 851.06382979,
      "QuantityRemaining": 0.0,
      "Commission": 0.0,
      "Price": 0.02,
      "PricePerUnit": 2.35E-05,
      "IsConditional": false,
      "Condition": "",
      "ConditionTarget": 0.0,
      "ImmediateOrCancel": true,
      "Closed": "2019-04-30T18:59:15.47"

**Comment by JKorf** [comment]
Ah, didnt know that would be a null (not really clear when null or 0 is returned by bittrex). I've just pushed version 3.1.2 which should be available in a few minutes.

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
Perfect, thanks.
