### ISSUE TITLE
Deposits/Withrawals Endpoint

### ISSUE THREAD

**Issue by ryanfalzon** [JKorf/Bittrex.Net#149]
Why is the deposits and withdrawals endpoint returning an error not found?

**Comment by JKorf** [comment]
Hi, what endpoints do you mean and what is the exact error you get?

**Comment by ryanfalzon** [comment]
I am using the following function client.GetDeposit("id");
This return a not found error.

**Comment by JKorf** [comment]
Are you sure the id is correct? For me this works:
````C#
var deposits = clientV3.GetClosedDeposits();
var deposit = clientV3.GetDeposit(deposits .Data[0].Id);
````
