### ISSUE TITLE
Bittrex Socket returns Null Object on QuerySummaryStates 

### ISSUE THREAD

**Issue by janvictor** [JKorf/Bittrex.Net#150]
Hi, 

The issue regards BittrexSocketClient:

After SubscribeToMarketSummariesUpdate I recieved Data succesfully via async QuerySummaryStates. This gave me a Mutable List of BittrexStreamMarketSummary Objects.

Since today I recieve null Object in this field.

Can you reproduce? It's strange as it worked so far.

best regards,
janvictor

**Comment by JKorf** [comment]
Hi, the QuerySummaryStates seem to work for me. Can you share some of your code?

**Comment by janvictor** [comment]
Hi,

Code wouldn't make sense as I am using VL. But maybe you could read from the stream if i missed something? It works now, but only sometimes, it's not a stable connection.

Client is Created @Create Function (White Lines), 
Subsription is hit OnOpen, and then QuerySummaryStates is Nested within async loop. 

![SocketQuerySummaryStates](https://user-images.githubusercontent.com/50916689/58252824-51dc3400-7d67-11e9-8870-9c210486f2b7.PNG)

**Comment by JKorf** [comment]
I'm not sure what I'm looking at haha. Anyway, could you maybe enable Debug logging in the BittrexSocketClientOptions and check what the logging says when it returns null?

**Comment by janvictor** [comment]
I will do! Still i believe the issue is not with your contribution. 
For now I will work with REST Client instead of socket.

I will let you know what was going on.
Thanks!
