### ISSUE TITLE
BittrexOrderV3 GetClosedOrdersAsync() return System.NullReferenceException

### ISSUE THREAD

**Issue by ewrdietsch** [JKorf/Bittrex.Net#151]
When I use **'GetClosedOrdersAsync()'**  or **'GetOpenOrdersAsync()'**  it returns a **'System.NullReferenceException'**. I don't know why that is happening, it didn't happen before. This is part of the code I am using.

**'bittrexClientV3'** is a global variable declared by **'BittrexClientV3'**. I use others from API V3 and everything works fine.

How can this error be resolved?

           try
            {
                WebCallResult<BittrexOrderV3[]> _OrdersResult = await bittrexClientV3.GetClosedOrdersAsync();

                if (_OrdersResult.Success)
                {
                }
                else
                {
                }

                return new Tuple<bool, BittrexOrderV3[], string>(_OrdersResult.Success, _OrdersResult.Data, _OrdersResult.Error.Message);
            }
            catch (NullReferenceException ex)
            {
                MessageBox.Show("CLOSED ORDER:" + ex.Message + " - " + ex.Source);
                return new Tuple<bool, BittrexOrderV3[], string>(false, null, "");
            }

**Comment by JKorf** [comment]
Hi, the calls seem to work fine on my end. I do notice on this line
`return new Tuple<bool, BittrexOrderV3[], string>(_OrdersResult.Success, _OrdersResult.Data, _OrdersResult.Error.Message);` 
you always access `_OrdersResult.Error.Message`, however if the call is successful then `_OrdersResult.Error` will be null, so accessing the `Message` property would throw a null reference. You'd probably want to change that to `_OrdersResult.Error?.Message`. Don't know if that is the problem you're seeing though.

**Comment by ewrdietsch** [comment]
Thanks,
this work after changing this part... **_OrdersResult.Error?.Message**
