### ISSUE TITLE
Bittrex V3 API Updates

### ISSUE THREAD

**Issue by pwnzya** [JKorf/Bittrex.Net#152]
There have been some changes/additions to Bittrex V3 API.
@JKorf , please, check them out.  Thanks.

From [Bittrex Changelist 08/08/2019](https://bittrex.zendesk.com/hc/en-us/articles/360032150691-Changelist-08-08-2019) :
> V3 API: Get all tickers
> 
> You can now use the v3 API to retrieve the bid/ask/last for all markets at once by getting v3/markets/ticker instead of querying each market individually.
> 
> V3 API: Currency logos
> 
> When getting currency information from v3/currencies the response will now include a URL for an image containing the currency's logo.

From [Bittrex Changelist 06/26/2019](https://bittrex.zendesk.com/hc/en-us/articles/360029636612-Changelist-06-26-2019) :
> V3 API Support for Ceiling Sell Orders
> 
> Ceiling Sell orders have been added to the V3 API Beta. This option allows you to instruct the system to sell enough of the base currency to increase your account balance of the quote currency by the specified amount.

**Comment by JKorf** [comment]
Hi thanks for the update, I've just a new version, should be available in a bit.
