### ISSUE TITLE
NotImplementedException Bittrex.Net.BittrexSocketClient.Unsubscribe

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bittrex.Net#154]
16:15:58.59[2]FATAL:UnobservedTaskException: AggregateException:
NotImplementedException:The method or operation is not implemented.:   at Bittrex.Net.BittrexSocketClient.Unsubscribe(SocketConnection connection, SocketSubscription s)
   at CryptoExchange.Net.Sockets.SocketConnection.<Close>d__53.MoveNext()

**Comment by JKorf** [comment]
That is expected. Sadly the current Bittrex API implementation doesn't support unsubscribing from socket streams.

**Comment by NektoDron** [comment]
Can you prevent the exception from being called? Because it cannot be controlled, it goes at the library level and this exception isn't handled.

**Comment by JKorf** [comment]
I'm not sure it shouldn't be raised though. If you call the method on the BittrexSocketClient it's a programming error right? If you can just call the method and continue people won't be aware that they aren't actually unsubscribed and data will still be streamed.

**Comment by NektoDron** [comment]
I didn't call any Unsubscribe methods. The library calls it itself during reconnects if connection was lost.

**Comment by JKorf** [comment]
Ah I see, my bad. I'll fix that then yes.

**Comment by JKorf** [comment]
Hi, I've pushed a new version in which this should be fixed.
