### ISSUE TITLE
When I Place Order Async V3 I get MARKET_NAME_REVERSED

### ISSUE THREAD

**Issue by ewrdietsch** [JKorf/Bittrex.Net#155]
When I place order to buy XRP at V3 API.

The Code:
var placedOrder = bittrexClientV3.PlaceOrderAsync(element.MarketName, OrderSide.Buy, OrderTypeV3.Limit, coinToBuy, TimeInForce.ImmediateOrCancel, PriceToBuy);

I get 
[Server error: MARKET_NAME_REVERSED]

**Comment by JKorf** [comment]
Well based on the error message, did you try to put the market name the other way around?
Instead of ETH-BTC try BTC-ETH for example
