### ISSUE TITLE
Socket API - QuerySummaryStates : JSON Deserialization error

### ISSUE THREAD

**Issue by MacSIME** [JKorf/Bittrex.Net#156]
Hi,

Got a deserialization error while querying a time QuerySummaryStates on SokcetAPI before using subscribing to SubscribeToMarketSummariesUpdate :

Looks like the error come from BittrexStreamMarketSummary class : Bid and Ask properties are not Nullable as the error is raised by "B" deserialization (referring to the Bittrex API doc)

In the V1 API, BittrexMarketSummary class has Bid and Ask nullable properties.

Could you fix it please ? :)

Many thanks !

**Comment by JKorf** [comment]
Hi thanks for the report, I've pushed a new version with nullable ask/bid properties. Should be available in a few minutes!

**Comment by MacSIME** [comment]
Many thanks for the fix, it works properly ! :)
