### ISSUE TITLE
GetSymbolSummariesAsync Symbol is empty

### ISSUE THREAD

**Issue by Bozzano13** [JKorf/Bittrex.Net#159]
Hello,
The request GetSymbolSummariesAsync  return empty string symbol.

regards,

**Comment by Bozzano13** [comment]
[JsonProperty("MarketName")] is missing in BittrexSymbolSummary.cs

**Comment by JKorf** [comment]
Hi thanks for the report, I've pushed a new version with a fix. If you run into any more problems, please let me know.
