### ISSUE TITLE
Make BittrexClient class more extendable (private -> protected)

### ISSUE THREAD

**Issue by arcastro** [JKorf/Bittrex.Net#16]
Hi,

Please change the access modifier for `ExecuteRequest` and `GetUrl` from `private` to `protected` 

https://github.com/JKorf/Bittrex.Net/blob/4a48942fd31e409ae060bc044af0517de33fc9a5/Bittrex.Net/BittrexClient.cs#L546

https://github.com/JKorf/Bittrex.Net/blob/4a48942fd31e409ae060bc044af0517de33fc9a5/Bittrex.Net/BittrexClient.cs#L609

This would make the class easier to extend. One use-case would be for consumers of this library to implement undocumented apis not currently supported by this library, such as

````
https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=BTC-WAVES&tickInterval=thirtyMin&_=1499127220008
````

Thanks,
Alan Castro

**Comment by cooljbg** [comment]
Reference for API v2.0
https://github.com/thebotguys/golang-bittrex-api/wiki/Bittrex-API-Reference-(Unofficial)

**Comment by JKorf** [comment]
I'll adjust the access modifiers. I'll also add the GetTicks endpoint in the wrapper. I don't see any other endpoint in the v2.0 reference that would provide more functionality then currently provided, you agree?

**Comment by JKorf** [comment]
I've added the GetTicks and LatestTick endpoints (as GetCandles and GetLatestCandle) and also made the ExecuteRequest and GetUrl methods protected.

If you have any other questions let me know.
