### ISSUE TITLE
Error on BittrexSocketClient.GetOrderBookAsync

### ISSUE THREAD

**Issue by daerhiel** [JKorf/Bittrex.Net#160]
Hi J,

I have started to get an error after updating package to v4.0.2:
``Failed to invoke proxy: There was an error invoking Hub method c2.GetOrderBook``.

![Annotation 2019-10-26 012217](https://user-images.githubusercontent.com/485120/67607991-14088f00-f78f-11e9-8620-f550b08a6b85.png)

Do you have any idea what might that be?

Sincerely,
Andrey.

**Comment by JKorf** [comment]
Hi Andrey, you're right. While doing some refactoring the command for Bittrex server was accidentally changed, resulting in it not being recognized anymore. I've fixed it and it should be working in version 4.0.3 which I just pushed.

Thanks for the report, let me know if you run into any other issues.

**Comment by daerhiel** [comment]
Hi J, thanks for quick response :) everything's working fine now.
