### ISSUE TITLE
Error on SubscribeToSymbolSummariesUpdateAsync

### ISSUE THREAD

**Issue by daerhiel** [JKorf/Bittrex.Net#161]
Hi J,

There's probably another similar issue, but it's intermittent for some reason, occurs quire rare.

Could you please look at it?

![Annotation 2019-11-02 005849](https://user-images.githubusercontent.com/485120/68059007-fcd81d00-fd0b-11e9-9ccd-558b57d15e9b.png)

**Comment by JKorf** [comment]
Hi, I'm not sure what the cause of the error would be, the library just calls the SignalR HubProxy.Invoke method which sometimes fails apparently. It doesn't provide any info why it fails though. 
Anyway, I've added a retry mechanism for the Invoke method. Please let me know if that helps.

**Comment by daerhiel** [comment]
Yeah, it's strange, cause it occurs very rare. But that's the only method that raises it.. The other subscription methods work fine..
I'll monitor it for a while.

**Comment by JKorf** [comment]
Have you seen any more issues with this?

**Comment by daerhiel** [comment]
Good question, btw, no. It seems it has disappeared, and I don't know why. I think it can be closed.

**Comment by JKorf** [comment]
Well I did at 2 retries if the call fails, so apparently a retry fixes the issue. Good it's been resolved.
