### ISSUE TITLE
Deserialize JsonReaderException in "GetClosedOrdersAsync () and GetOpenOrdersAsync()"

### ISSUE THREAD

**Issue by ewrdietsch** [JKorf/Bittrex.Net#163]
Hi,
I am receiving an exception when I call **"GetClosedOrdersAsync () and GetOpenOrdersAsync()"**, the data received is fine, but the debugger registers the exception **"JsonReaderException"**.

Here the call to **"GetClosedOrdersAsync ()"**:

- _WebCallResult <IEnumerable > Orders = await bittrexClientV3.GetClosedOrdersAsync ();_

Here the exception **"JsonReaderException"** in the data received and is as follows:

- _2019/11/26 00: 24: 04: 568 | Error | Deserialize JsonReaderException: Unexpected character encountered while parsing value: e. Path '', line 0, position 0., LinePosition: 0. Data: error code: 1015_

**Comment by JKorf** [comment]
Hi,
I'm assuming we're talking about Bittrex instead of Bitfinex, but that's okay. I don't have any errors in the output when requesting closed orders. You're saying the data you get in the result is fine but still get an exception in the output?

**Comment by ewrdietsch** [comment]
When I use **the diagnostic tool** of the **visual studio** I get the following exceptions:

![Diagnostic tools](https://user-images.githubusercontent.com/12518485/70645528-8fc57a80-1c1b-11ea-99fa-59a4a4c21ecb.png)

but the data **arrives well**:

![Order Close and Open](https://user-images.githubusercontent.com/12518485/70645622-b7b4de00-1c1b-11ea-992e-ab0d109b7bd3.png)

how can we correct so that this exception does not happen.

**Comment by JKorf** [comment]
Sorry for the late response, I've been busy. It looks like you're polling the server, but the server sometimes returns an error code. I assume you ignore the result if WebCallResult.Success == false, so you don't really have any problems with it right?

I'll push a fix that removes this logging when trying to parse an error response.
