### ISSUE TITLE
Bittrex API v3 Updates - Now ready for production including v3 Socket

### ISSUE THREAD

**Issue by pwnzya** [JKorf/Bittrex.Net#164]
There have been some major changes/additions to Bittrex API v3.

"**_The v3 API has reached general availability and is ready for production use! (v3 SOCKET is ready)_**"

@JKorf, please, check them out. Thanks.

From [Bittrex API v3 Doc](https://bittrex.github.io/api/v3)
> Change Log
>
> 06/17/2020
> 
> - **The v3 API has reached generally availability and is ready for production use!**
> - You can now get the list of executed trades related to your orders from GET /orders/{orderId}/executions
> - **End of life for the v1 api is planned for 9/30/2020**
> 
> 06/10/2020
> 
> - The baseVolume property was removed from MarketSummary and Candle responses. Use the quoteVolume property for quote volume or the volume property for base volume.
>
> 05/27/2020
> 
> - Successful cancel withdrawal response will change from 204 with no content in the response body to a 200 with the cancelled withdrawal in the response body
> - Historical candles endpoint will no longer allow you to specify more portions of the date parameters than are necessary for the selected candle interval. Specify only year for day candles. Specify only year and month for hour candles.
> - GET /candles endpoint is deprecated and has been removed from the documentation. Use GET /candles/{interval}/recent instead. The response model is the same.
>
> 05/15/2020
> 
> - **V3 SOCKET IS NOW IN PUBLIC BETA** ([Overview](https://bittrex.github.io/api/v3#topic-Websocket-Overview))
> - May now trigger ceiling orders from conditional orders
> - Order object now includes the order's OCO partner (if applicable)
> - May now get whitelisted withdrawal addresses from /withdrawals/whitelistAddresses
> - Balance object now has an updatedAt timestamp
> - Markets and currencies now indicate if they are prohibited from use by US customers
> - You can now get your accountId from the account endpoint
> - Deposit object now includes whether a deposit source was blockchain, wire transfer, or credit card
> 
> 01/27/2020
> 
> - **Conditional orders (e.g. stop loss) have been added to the V3 API Beta. See the new Placing Conditinal Orders section below for additional information.**
> 
> - **Historical candles are now available in the API**
> 
> - **The functionality of the existing candles endpoint has been duplicated into a candles/.../recent endpoint. The existing one will be retired in a future release.**

From [Bittrex Changelist 05/20/2020](https://bittrex.zendesk.com/hc/en-us/articles/360043236292-Changelist-5-20-2020)

> API Changes
> - The [v3 websocket](https://bittrex.github.io/api/v3/#topic-Websocket-Overview) is now in public beta!  <Note: that link won't actually work until we ship and have published the docs> 
> - Ceiling orders maybe be placed from conditional orders
> - v3 Markets and currencies now indicate if they are prohibited from use by US customers
> - Additional changes listed [here](https://bittrex.github.io/api/v3#topic-Change-Log)

From [Bittrex Changelist 02/07/2020](https://bittrex.zendesk.com/hc/en-us/articles/360039539231-Changelist-02-07-2020)

> Bittrex.com
> 
> We’ve rolled out a new Trading Experience, available now in Bittrex Preview.  
> 
> - Improved charting, featuring TradingView with real-time updates 
> - Trading on the chart for Limit, Ladder Limit and Conditional orders 
> - **New Ladder Limit order type** 
> - Six selectable adaptive page layouts and themes to fit your trading style 
> - The ability to quickly pivot to important markets within wallets 
> - Account management improvements 
> - And more.. 
>
> API
> 
> **Candle results returned from the v3 API will now include 0-volume candles for time periods during which no trades took place, with OHLC equal the previously closed value.**

**Comment by JKorf** [comment]
I've updated the Rest API to the latest V3 documentation and added the V3 socket client
