### ISSUE TITLE
BittrexKlineV3 - BaseVolume not being populated

### ISSUE THREAD

**Issue by cryptocrunch** [JKorf/Bittrex.Net#168]
In the V3 release of BitTrex on 6/10, BaseVolume was removed/renamed to QuoteVolume which causes the results not to be returned from the call.

06/10/2020

The baseVolume property was removed from MarketSummary and Candle responses. Use the quoteVolume property for quote volume or the volume property for base volume.

**Comment by JKorf** [comment]
Should be fixed in the latest version

**Comment by cryptocrunch** [comment]
@JKorf - It does, thank you!
