### ISSUE TITLE
GetHistoricalKlines' month and day parameters need to be optional

### ISSUE THREAD

**Issue by pwnzya** [JKorf/Bittrex.Net#169]
Hello @JKorf.  Thanks for updating Bittrex.Net to V3!

The issue is as follows:

For KlineInterval = HOUR_1, only year and month must be specified, not day.  If day is specified, error is returned from the server.
Example:
- https://api.bittrex.com/v3/markets/BTC-USDT/candles/HOUR_1/historical/2017/1/1 returns error.
- https://api.bittrex.com/v3/markets/BTC-USDT/candles/HOUR_1/historical/2017/1 returns candles.

For KlineInterval = DAY_1, only year must be specified, not month and day.  If month and day are specified, error is returned from the server.
Example:
- https://api.bittrex.com/v3/markets/BTC-USDT/candles/DAY_1/historical/2017/1/1 returns error.
- https://api.bittrex.com/v3/markets/BTC-USDT/candles/DAY_1/historical/2017/1 returns error.
- https://api.bittrex.com/v3/markets/BTC-USDT/candles/DAY_1/historical/2017 returns candles.

Bittrex API Document Change Log 05/27/2020 states:
"Historical candles endpoint will no longer allow you to specify more portions of the date parameters than are necessary for the selected candle interval. Specify only year for day candles. Specify only year and month for hour candles."

**Comment by JKorf** [comment]
Thanks for the report, it's been fixed in the latest version!
