### ISSUE TITLE
GetOrderHistory not working?! 

### ISSUE THREAD

**Issue by TomdeWinter** [JKorf/Bittrex.Net#17]
Hi,

I am getting along just fine. Only thing is now 
var orderHistory = client.GetOrderHistory("BTC-NEO");
is returning success but the collection is empty?

I expected a collection with the history of NEO but it has 0 elements.
Other functions llike GetBalance and GetBalances work just fine.

Can you help me finding the issue here?

Thanks and regards,

Tom

**Comment by JKorf** [comment]
Hello,

Is your last order on NEO by any chance more than a month ago? The API only provides order data from less than a month ago. To get the full history you can manually download your order history from the website. Sadly I can't help you regarding this.

**Comment by TomdeWinter** [comment]
Hello,

Excellent feedback. 
Indeed the last order was over a month ago. I couldnt find this information anywhere. Where did you get this info from?
Thanks a bunch!

**Comment by JKorf** [comment]
It isn't mentioned anywhere in the API documentation, however I came across this exact issue myself some time back. If you search for 'Bittrex order history' or something along that lines on google multiple posts of people with this issue come up. 
For example:
https://www.reddit.com/r/CryptoCurrency/comments/6dsjqy/bittrex_api_does_not_return_order_history_older/
