### ISSUE TITLE
Question: V3 Socket SubscribeToKlineUpdates Behavior

### ISSUE THREAD

**Issue by pwnzya** [JKorf/Bittrex.Net#177]
When running the following code:
```c#
/// <summary>
/// Tests behavior of socket client when subscribing to OneMinute and OneHour interval kline updates for BTC-USD
/// </summary>
private async Task<bool> TestSubscribeToKlineUpdates()
{
  ...
  string marketSymbol = "BTC-USD";
  // Subscribe to "one MINUTE" interval kline updates for "BTC-USD"
  var result1 = await socketClientV3.SubscribeToKlineUpdatesAsync(marketSymbol, KlineInterval.OneMinute, updateData=>HandleOneMinuteKlineUpdates(updateData));
  // Subscribe to "one HOUR" interval kline updates for "BTC-USD"
  var result2 = await socketClientV3.SubscribeToKlineUpdatesAsync(marketSymbol, KlineInterval.OneHour, updateData=>HandleOneHourKlineUpdates(updateData));
  ...
}

/// <summary>
/// Prints all OneMinute kline update details received
/// </summary>
private void HandleOneMinuteKlineUpdates(BittrexKlineUpdate updateData)
{
  ...
  // string updateDetails = "<update details>"
  Console.WriteLine($"{updateDetails} <-- Output by OneMinute UpdatesHandler");
}

/// <summary>
/// Prints all OneHour kline update details received
/// </summary>
private void HandleOneHourKlineUpdates(BittrexKlineUpdate updateData)
{
  ...
  // string updateDetails = "<update details>"
  Console.WriteLine($"{updateDetails} <-- Output by OneHour UpdatesHandler");
}
```
it prints the same update data twice...
```
OUTPUT:
<BTC-USD OneMinute update details> <-- Output by OneMinute UpdatesHandler
<BTC-USD OneMinute update details> <-- Output by OneHour UpdatesHandler
<BTC-USD OneHour update details> <-- Output by OneMinute UpdatesHandler
<BTC-USD OneHour update details> <-- Output by OneHour UpdatesHandler
   .
   .
   .
```
which means both updates handlers, HandleOneMinuteKlineUpdates() and HandleOneHourKlineUpdates(), are handling OneMinute updates and OneHour Updates, contrary to my expectation of each handling only OneMinute or OneHour updates.

Does this mean I am using twice the bandwidth of the socket connection?

I was wondering if this is 
- Bittrex API's behavior as intended, or its bug
- Your library Bittrex.Net/CryptoExchange.Net's behavior as intended, or their bug
- My code's bug, or I'm missing something

Thanks.

Update:
My guess is that the socket is receiving the updates just once, so connection bandwidth is not wasted, but, in the case of above code, since the two handers are registered in the socket client mechanism, the same update data is printed twice. In that case, I can simply filter the data by BittrexKlineUpdate.Interval in each handler when processing the updates.  Originally, I was using the same update handler for both OneMin and OneHour updates, so I could not do this...

Update2:
It seems to be working - having separate handlers for each interval, and filtering update data by appropriate interval, did the trick.

Update3:
If I subscribed to multiple markets(**_marketSymbol1_**, **_marketSymbol2_**, **_marketSymbol3_**) OneMinute interval kline updates using 
```c#
public async Task<CallResult<UpdateSubscription>> SubscribeToKlineUpdatesAsync(IEnumerable<string> symbols, KlineInterval interval, Action<BittrexKlineUpdate> onUpdate)
```
and registered a handler in the socket client, and later on, if I subscribed to a new market **_marketSymbol4_** using
```c#
public Task<CallResult<UpdateSubscription>> SubscribeToKlineUpdatesAsync(string symbol, KlineInterval interval, Action<BittrexKlineUpdate> onUpdate) => SubscribeToKlineUpdatesAsync(new[] {symbol}, interval, onUpdate);
``` 
and registered a new handler for it,
then,
there will be two handlers processing the updates for **_marketSymbol4_** if filtered the updates using both market name and interval in the second handler.  If I filtered the input only by the interval in the second handler, all four markets' updates will be processed twice.

To avoid this, I would have to pass a dummy handler that does nothing for **_marketSymbol4_**...

After all, maybe this is something to think about...

**Comment by JKorf** [comment]
You're right, that was not intended behavior. I've fixed it in the latest version.
