### ISSUE TITLE
Minor updates to Bittrex v3 API including conditional order web socket.

### ISSUE THREAD

**Issue by standimj** [JKorf/Bittrex.Net#179]
First off, thanks for such great work.  Just posting this here for the back log from https://bittrex.github.io/api/v3

09/23/2020

You now cancel all of your open orders or all of your open orders on a market with DELETE /orders/open
**Websocket stream for conditional orders is now available**
Withdrawal requests can now be made idempotent by specifying a clientWithdrawalId
Simple examples of authenticating and subscribing to the websocket in C#, Node.js, Python, and Java may be found in the Examples section
Currency model now contains Bittrex's blockchain base address
Currency and Market models now reference any additional required terms of service agreeements

**Comment by JKorf** [comment]
Thanks for the heads up, I've incorporated the changes in the latest version.
