### ISSUE TITLE
GetOpenOrdersAsync don't respect symbol parameter

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/Bittrex.Net#180]
Hi,
I notice that in the code for  GetOpenOrdersAsync, le symbol is correctly put into a parametrer dictionary, but this one is not used anymore. I think it should be passed to SendRequest.

Hope it help.

Eric

public async Task<WebCallResult<IEnumerable<BittrexOrderV3>>> GetOpenOrdersAsync(string? symbol = null, CancellationToken ct = default)
        {
            var parameters = new Dictionary<string, object>();
            parameters.AddOptionalParameter("marketSymbol", symbol);

            return await SendRequest<IEnumerable<BittrexOrderV3>>(GetUrl("orders/open"), HttpMethod.Get, ct, signed: true).ConfigureAwait(false);

        }

**Comment by JKorf** [comment]
Thanks for the heads up, I've fixed it in the latest version.
