### ISSUE TITLE
Incorrect pageSize limit?

### ISSUE THREAD

**Issue by dlmac** [JKorf/Bittrex.Net#181]
https://github.com/JKorf/Bittrex.Net/blob/875dcf89b75b5f22a42c91a44c721769d78853bc/Bittrex.Net/BittrexClientV3.cs#L647

https://bittrex.github.io/api/v3#operation--orders-closed-get

Should be able to set 200?

**Comment by JKorf** [comment]
Thanks for the report. You're right, I've fixed this in the latest version.
