### ISSUE TITLE
New v3 changes 12/02/2020

### ISSUE THREAD

**Issue by standimj** [JKorf/Bittrex.Net#184]
Hi Jkorf, thank you for your amazing work.  Latest change log adds the following.  The market executions streaming socket would be amazing as well as the REST endpoints and market currency data are high on my wish list.  For your consideration.  Thank you.

12/02/2020

**There is now a socket stream for executions! As well as a corresponding set of REST endpoints for retrieving historical executions and synchronizing.**

You can now place or cancel multiple orders with a single request using the /batch endpoint

**Determining which markets and currencies you have access to can now be done more easily and explicitly via the market permissions and currency permissions endpoints**

It is now possible to retrieve market candles based on the midpoint between best bid ad ask in addition to candles based on trade prices (note that midpoint candles from prior to 12/2 are not available)

The /withdrawals/whitelistAddresses endpoint has been renamed to /withdrawals/allowed-addresses for clarity. The old name will continue to work.

**Comment by JKorf** [comment]
I've implemented these in the latest version

**Comment by standimj** [comment]
Thank you so much!  Thank you for cleaning up the V3 naming as well.  Was easy to refactor and very clean.
