### ISSUE TITLE
GetHistoricalKlines interval Problem

### ISSUE THREAD

**Issue by bydevelopertr** [JKorf/Bittrex.Net#185]
Hi Dear Jkorf,

I use Bittrex historical Klines but all the time get this error: {"Can't specify day value when using hour interval"}

I can't convert 1d interval to DAY_1.  Because historical Kline different getkline method:
Example:
https://api.bittrex.com/v3/markets/BTC-USDT/candles/DAY_1/historical/2020.

i want to ask that: How do I use X GetHistoricalKlines ? How do I convert Kline interval ?
I could not see any examples.

I need you help and best regards.

Thank you.

**Comment by pwnzya** [comment]
Hi @bydevelopertr ,

I guess this might help you: #169 

For KlineInterval = HOUR_1, only year and month must be specified, not day.  If day is specified, error is returned from the server.
Example:
- https://api.bittrex.com/v3/markets/BTC-USDT/candles/HOUR_1/historical/2017/1/1 returns error.
- https://api.bittrex.com/v3/markets/BTC-USDT/candles/HOUR_1/historical/2017/1 returns candles.

So, in Jkorf's Bittrex.Net library code, he is checking user input, making sure day value is not sent to the Bittrex server when users want HOUR_1 candles.

**Comment by bydevelopertr** [comment]
@pwnzya hi,

You right but I need GetHistoricalKlines. This code get exception:

var klines = client.GetHistoricalKlines("XLMUSDT", Bittrex.Net.Objects.KlineInterval.OneHour, year, month, day, cts);
Exceptin:  {"Can't specify day value when using hour interval"}

Did you make an example of this?

**Comment by pwnzya** [comment]
Example would be something like below.
( Note that I did not provide "day" parameter to the method GetHistoricalKlines. )
```c#
private void TestGetHistoricalKlines()
{
    string marketSymbol = "BTC-USDT";
    KlineInterval interval = KlineInterval.OneHour;
    int year = 2017;
    int month = 1;

    // *** Omitting the code to set up Bittrex REST API client ***

    try
    {
        var result = BittrexRestClient_V3.GetHistoricalKlines(marketSymbol, interval, year, month);

        if (result.Success)
        {
            var count = result.Data.Count();
            var firstCandleTimestamp = result.Data.First().StartsAt;
            var lastCandleTimestamp = result.Data.Last().StartsAt;
            ConsoleWriteLine($"Received {count} candles for {marketSymbol} ({interval}).");
            ConsoleWriteLine($"First candle timestamp = {firstCandleTimestamp:yyyy/MM/dd HH:mm:ss:fff}");
            ConsoleWriteLine($"Last candle timestamp  = {lastCandleTimestamp:yyyy/MM/dd HH:mm:ss:fff}");
        }
        else
        {
            ConsoleWriteLine($"Failed to receive candles for {marketSymbol} ({interval}).");
            ConsoleWriteLine($"ResponseStatusCode = {result.ResponseStatusCode}");
            ConsoleWriteLine($"Error = {result.Error}");
        }
    }
    catch(Exception exception)
    {
        ConsoleWriteLine($"Exception: {exception.Message}");
    }
}
```

If I provided day value like below, it will throw the exception:
```c#
        int day = 1;
        var result = BittrexRestClient_V3.GetHistoricalKlines(marketSymbol, interval, year, month, day);
```
If you want to get more one-hour historical candles for before or after 2017/1, then you have to call the method for that year/month, for example 2016/12 or 2017/2.

More detail is written in the official Bittrex API documentation.
