### ISSUE TITLE
Could not create SSL/TLS secure channel problem, Any Ideas

### ISSUE THREAD

**Issue by mmeents** [JKorf/Bittrex.Net#187]
**Describe the bug**
So trying to use the library and no luck, get the following message when attempting get summaries: 
An error occurred while sending the request. The request was aborted: Could not create SSL/TLS secure channel.

Attempted using BittrexClient and BittrexClientV3, same result.  

**To Reproduce**
        var client = new BittrexClient();
        client.SetApiCredentials(sPub, sPri);
        var Tickers = client.GetSymbolSummaries();

**What am I missing?**

**Comment by JKorf** [comment]
Have you tried this?

https://stackoverflow.com/a/2904963

**Comment by mmeents** [comment]
That was the fix.  

Thank you
