### ISSUE TITLE
No response on API call

### ISSUE THREAD

**Issue by fernanespejo** [JKorf/Bittrex.Net#19]
Hi there,

I am trying to use the GetMarkets method and my app keeps hanging because no result comes back from Bittrex API? Here's my snippet:

```
BittrexClient client = new BittrexClient();
var result = client.GetMarkets();

if (result.Success)
{
    //do stuff
}
```

**Comment by JKorf** [comment]
Hi, that seems to work fine on my end. Are you by any chance trying to run this in the user interface thread? (for example in the OnLoad method, or OnButtonClick) If so, you need to wrap it in a Task, like so:
```C#
Task.Run(()=>{
    BittrexClient client = new BittrexClient();
    var result = client.GetMarkets();

    if (result.Success)
    {
        //do stuff
    }
}
```

**Comment by fernanespejo** [comment]
Amazing, this did the trick, thanks!
