### ISSUE TITLE
Failing to build on Linux due to icon folder case mismatch

### ISSUE THREAD

**Issue by shigengyu** [JKorf/Bittrex.Net#190]
**Describe the bug**
Build failing on Linux due to "icon" folder case mismatch.

**To Reproduce**
Build the solution under Linux.

**Expected behavior**
Change "icon" folder name in project file to "Icon".

**Debug logging**
/usr/share/dotnet/sdk/5.0.201/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(221,5): error : Could not find a part of the path '/work/tychon-csharp/Bittrex.Net/Bittrex.Net/icon'.

**Comment by JKorf** [comment]
You also submitted PR's for the other implementations, however there you also changed the FrameworkVersion and sdk versions? Is that intentional?

**Comment by shigengyu** [comment]
Sorry, that wasn't intentional. Was trying to create PR from a branch in my forked repo to your master, and Github does not allow me do it.

**Comment by shigengyu** [comment]
Recreated PR for Bitfinex and Kraken. I think CI for Huobi is broken due to sdk version mismatch.

**Comment by JKorf** [comment]
Both .travis.yml and the global.json have version 5.0.103, so it should work

**Comment by shigengyu** [comment]
Recreated PR, worked this time.

**Comment by JKorf** [comment]
Thanks, merged all
