### ISSUE TITLE
Batch of Requests

### ISSUE THREAD

**Issue by Guftel** [JKorf/Bittrex.Net#196]
Hi, big thanks for your time and your work. Its just a charm to work with it.

I have a short question, is it possible to create a batch of Requests (Orders) - if yes, How ?

Best regards

**Comment by JKorf** [comment]
Hi, this was something that was missing in the implementation, but I've added it to the latest version which adds 2 new endpoints: 
PlaceMultipleOrders and CancelMultipleOrders, you can use these to send a batch request.
