### ISSUE TITLE
Getclosedorders error after instant buy/sell on web interface

### ISSUE THREAD

**Issue by Husky36** [JKorf/Bittrex.Net#197]
**Describe the bug**
I have used instant buy function in bittrex web site:
![image](https://user-images.githubusercontent.com/78642002/116787054-42f97280-aaa2-11eb-9591-55878947fba2.png)
After that, i have now an error on getclosedorders api function (see log).

**To Reproduce**
order = client.GetClosedOrders();

**Expected behavior**
![image](https://user-images.githubusercontent.com/78642002/116787171-fbbfb180-aaa2-11eb-9c92-db5860b07835.png)
The data field is empty. Only error message.

**Debug logging**
{: Deserialize JsonSerializationException: Error setting value to 'TimeInForce' on 'Bittrex.Net.Objects.BittrexOrder'. 2.29144527","commission":"1.61346029","proceeds":"215.12804041","status":"CLOSED","createdAt":"2021-04-17T03:16:54.88Z","updatedAt":"2021-04-17T03:16:54.88Z","closedAt":"2021-04-17T03:16:54.88Z"},{"id":"8480bcd3-0cd8-490e-afbc-60d711357ddd","marketSymbol":"NEO-USDT","direction":"BUY","type":"LIMIT","quantity":"2.29144527","limit":"91.88300000","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"2.29144527","commission":"1.57836216","proceeds":"210.44828824","status":"CLOSED","createdAt":"2021-04-17T01:05:54.6Z","updatedAt":"2021-04-17T01:05:54.6Z","closedAt":"2021-04-17T01:05:54.6Z"},{"id":"f8ecf12f-b59a-4b3a-be4b-49d6cf19aca3","marketSymbol":"LTC-USDT","direction":"SELL","type":"LIMIT","quantity":"0.66587708","limit":"318.74500000","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"0.66587708","commission":"1.60067110","proceeds":"213.42281385","status":"CLOSED","createdAt":"2021-04-17T01:03:54.55Z","updatedAt":"2021-04-17T01:03:54.55Z","closedAt":"2021-04-17T01:03:54.55Z"},{"id":"578a41e9-5f7b-4289-b599-f8ca27fb3f68","marketSymbol":"LTC-USDT","direction":"BUY","type":"LIMIT","quantity":"0.66587708","limit":"314.18800000","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"0.66587708","commission":"1.55788698","proceeds":"207.71826513","status":"CLOSED","createdAt":"2021-04-16T16:46:53.81Z","updatedAt":"2021-04-16T16:46:53.81Z","closedAt":"2021-04-16T16:46:53.81Z"},{"id":"3bc34f68-6a09-4136-8a1d-e294eba1602f","marketSymbol":"NEO-USDT","direction":"SELL","type":"LIMIT","quantity":"2.53787011","limit":"81.47700000","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"2.53787011","commission":"1.55828103","proceeds":"207.77080403","status":"CLOSED","createdAt":"2021-04-16T04:04:49.91Z","updatedAt":"2021-04-16T04:04:49.91Z","closedAt":"2021-04-16T04:04:49.91Z"},{"id":"c3cd173c-ab18-42c4-83bf-c493bb4601a6","marketSymbol":"NEO-USDT","direction":"BUY","type":"LIMIT","quantity":"2.53787011","limit":"80.31300000","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"2.53787011","commission":"1.51525622","proceeds":"202.03416325","status":"CLOSED","createdAt":"2021-04-16T01:38:50.21Z","updatedAt":"2021-04-16T01:38:50.21Z","closedAt":"2021-04-16T01:38:50.21Z"},{"id":"4675430d-9a80-45c2-b8ac-aa8362cf0986","marketSymbol":"LTC-USDT","direction":"SELL","type":"LIMIT","quantity":"0.73686975","limit":"282.56000000","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"0.73686975","commission":"1.56321332","proceeds":"208.42844594","status":"CLOSED","createdAt":"2021-04-16T01:36:49.66Z","updatedAt":"2021-04-16T01:36:50.03Z","closedAt":"2021-04-16T01:36:50.03Z"},{"id":"1ef09391-9249-4700-ab59-6b9138e05db6","marketSymbol":"LTC-USDT","direction":"BUY","type":"LIMIT","quantity":"0.73686975","limit":"280.33400000","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"0.73686975","commission":"1.54462724","proceeds":"205.95029945","status":"CLOSED","createdAt":"2021-04-14T22:35:45.24Z","updatedAt":"2021-04-14T22:35:45.24Z","closedAt":"2021-04-14T22:35:45.24Z"},{"id":"0a496d3d-cd1f-40d6-a447-8c1b98db4331","marketSymbol":"ADA-USDT","direction":"SELL","type":"MARKET","quantity":"158.43149042","timeInForce":"IMMEDIATE_OR_CANCEL","fillQuantity":"158.43149042","commission":"1.54246882","proceeds":"205.66250965","status":"CLOSED","createdAt":"2021-04-12T19:18:13.62Z","updatedAt":"2021-04-12T19:18:13.62Z","closedAt":"2021-04-12T19:18:13.62Z"},{"id":"138520d1-17b7-4cf1-839a-506b8dfd9864","marketSymbol":"ADA-USDT","direction":"BUY","type":"LIMIT","quantity":"158.43149042","limit":"1.30800000","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"158.43149042","commission":"1.53834512","proceeds":"205.11268267","status":"CLOSED","createdAt":"2021-04-06T13:12:38.95Z","updatedAt":"2021-04-06T13:12:38.95Z","closedAt":"2021-04-06T13:12:38.95Z"},{"id":"a5b5ea14-a6a7-4936-a219-925729b2a102","marketSymbol":"LTC-USDT","direction":"SELL","type":"LIMIT","quantity":"0.91034659","limit":"231.32700000","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"0.91034659","commission":"1.58697300","proceeds":"211.59640116","status":"CLOSED","createdAt":"2021-04-06T12:59:38.17Z","updatedAt":"2021-04-06T12:59:38.17Z","closedAt":"2021-04-06T12:59:38.17Z"},{"id":"a7b461d1-e7cc-4059-bdef-704fe7d7e256",

**Comment by Husky36** [comment]
I have update Bittrexorder.cs with:
![image](https://user-images.githubusercontent.com/78642002/116788183-8c4cc080-aaa8-11eb-8058-0587a3c5373c.png)

And its work again!

**Comment by JKorf** [comment]
I didn't know it was possible to be null, thanks for the heads up. I've fixed it in the latest version.
