### ISSUE TITLE
Enable accepting API base URL as constructor parameter

### ISSUE THREAD

**Issue by rutgervanwilligen** [JKorf/Bittrex.Net#20]
Could you possibly add an overload of the `BittrexClient` constructor with an extra parameter to override the Bittrex API base URL? This makes unit testing a whole lot easier (e.g. you would then be able make the client point to a mock HTTP server, serving mock JSON data, in order to test whether or not the client correctly handles/deserializes responses and error messages). It would enable us to test our application easier, too.

Once again, I'd be happy to help!

**Comment by JKorf** [comment]
Hi, that makes sense. I've added as requested, and I also gave the BittrexClient an interface to support mocking on a higher level. Hope this helps you!
