### ISSUE TITLE
PlaceOrderAsync has an error for OrderType.Ceiling and OrderType.CeilingLimit

### ISSUE THREAD

**Issue by dvpot** [JKorf/Bittrex.Net#202]
I think there is an error in PlaceOrderAsync.

I place a limit order, buy with BTC:
var result = await client.PlaceOrderAsync ("BTC-USDT", OrderSide.Buy, OrderType.Limit, TimeInForce.GoodTillCancelled, quantity: 0.0025m, limit: 40000.0m);
All is good.

I would like to place a limit order for USDT:
var result = await client.PlaceOrderAsync ("BTC-USDT", OrderSide.Buy, OrderType.CeilingLimit, TimeInForce.GoodTillCancelled, limit: 40000.0m, ceiling: 100.0m);
Throws an error because the quantity parameter is required. Although, according to the API documentation, this parameter is optional.

I tried to indicate as quantity: null
Returns error: INVALID_CEILING_LIMIT_BUY

**Comment by JKorf** [comment]
Hi, I think the issue is that `TimeInForce.GoodTillCancelled` is not valid for ceiling orders. See https://bittrex.github.io/api/v3#topic-Placing-Orders. Using `ImmediateOrCancel` for example it should work.

**Comment by dvpot** [comment]
Hi, I tested the following options:
1. var result = await client.PlaceOrderAsync (“BTC-USDT”, OrderSide.Buy, OrderType.Market, TimeInForce.ImmediateOrCancel, quantity: 20);
The order was executed, but not 20 USDT, but for all available funds (it's good that I had only 100 USDT for the test :) )

2. var result = await client.PlaceOrderAsync (“BTC-USDT”, OrderSide.Buy, OrderType.Market, TimeInForce.ImmediateOrCancel, quantity: 0, ceiling: 20);
Error: newOrder.Quantity ": [" Value must be a decimal, and must be greater than 0. "]

3. var result = await client.PlaceOrderAsync (“BTC-USDT”, OrderSide.Buy, OrderType.Market, TimeInForce.ImmediateOrCancel, quantity: 20, ceiling: 20);
Error: INVALID_ORDER_TYPE

4. var result = await client.PlaceOrderAsync (“BTC-USDT”, OrderSide.Buy, OrderType.Market, TimeInForce.ImmediateOrCancel, ceiling: 20);
This request cannot be made because no required parameter - quantity.

Are there options for how to make a purchase on the Market for USDT?

**Comment by Marcusbaker1** [comment]
Hi! 

This is working for me, I pass quantity as 0, limit as null and OrderType.CeilingMarket

var Result = await socketClient.PlaceOrderAsync(marketSymbol, OrderSide.Buy, OrderType.CeilingMarket, TimeInForce.ImmediateOrCancel, 0, null, 20);

Hope this helps!

**Comment by Marcusbaker1** [comment]
Hi, 

This is working for me. 

Pass Quantity and limit as null.

var Result = await socketClient.PlaceOrderAsync(marketSymbol, OrderSide.Buy, OrderType.CeilingMarket, TimeInForce.ImmediateOrCancel, null, null, 20);

Hope this helps!

**Comment by dvpot** [comment]
Hi,
Thanks!
It works.
