### ISSUE TITLE
Wrong prices in closed Orders

### ISSUE THREAD

**Issue by Guftel** [JKorf/Bittrex.Net#204]
Hello,
there where several times different prices in a closed order (BUY and SELL) compare do Bittrex. Some Prices even where never on the Market. Where could the Problem come from ?
there is a SubscribeToSymbolTickerUpdatesAsync() and SubscribeToOrderUpdatesAsync() active. The event from the OrderUpdates goes straight in to a database. So no manipulation inside the programm?

Best regards and still thanks for your great work.

**Comment by Guftel** [comment]
Hi, Thanks for you quick answer.

here two examples:

Today at 12:25 EUR-DFI (UTC+1)
Bittrex : €3.77100000
Recived : €3.39900000 (Price from 11:07 (UTC+1) ?)

Today at 12:50 EUR-DFI (UTC+1)
Bittrex : €3.90100000
Recived : €4.59700000 (much higher then the higest today)

**Comment by JKorf** [comment]
Hm, I can't really explain it. The best way to go I think is to enable `OutputOriginalData` in the client options, and log the value of the OriginalData in the DataEvent. That way you can check the data that was received vs what was recorded. If the price is wrong when received it's an issue on Bittrex` side, else it's somewhere in the client side (either the library or your code).

**Comment by Guftel** [comment]
Ok, I will do that. At the moment I made a workaround. Just request in the orderupdates-event to get the order again with the ID from the updateorder from the orderevent. Then compare the two prices - at the moment no wrong price until now.
