### ISSUE TITLE
Feature request: KlineInterval mapped to respective int value

### ISSUE THREAD

**Issue by alessandroparma** [JKorf/Bittrex.Net#210]
Would it be possible to jave all KLineInterval in XXX.Net.Enums mapped to their respective minutes in int format? It is clear that each API could have a different set of avaiable options for candles durations, but having it mapped to the int value (1:1 with minutes would simplify the conversione between the enums.
Thanks

**Comment by JKorf** [comment]
Hi, I've added this in the latest release. It's based on seconds instead of minutes though

**Comment by alessandroparma** [comment]
Thanks a lot!

 

Da: Jan Korf ***@***.***> 
Inviato: domenica 1 maggio 2022 19:19
A: JKorf/Bittrex.Net ***@***.***>
Cc: alessandroparma ***@***.***>; Author ***@***.***>
Oggetto: Re: [JKorf/Bittrex.Net] Feature request: KlineInterval mapped to respective int value (Issue #210)

 

Hi, I've added this in the latest release. It's based on seconds instead of minutes though
