### ISSUE TITLE
Stream quotes performance improvement

### ISSUE THREAD

**Issue by KaiserSozo** [JKorf/Bittrex.Net#22]
Hello there!

I suggest to improve performance by refactoring this part of code:

                foreach (var allRegistration in allRegistrations)
                    allRegistration.Callback(data.Deltas);

                foreach (var delta in data.Deltas)
                    foreach (var update in marketRegistrations.Where(r => r.MarketName == delta.MarketName))
                       update.Callback(delta);

of BittrexSocketClient.cs to use ParallelForEach to call callbacks for the different markets/deltas in parallel threads.

**Comment by JKorf** [comment]
Hi, fair point. This will be shipped in the next version

**Comment by JKorf** [comment]
This is implemented in the latest version.
