### ISSUE TITLE
Doesn't work with ASP.NET?

### ISSUE THREAD

**Issue by mariocaptain** [JKorf/Bittrex.Net#24]
Hi,

I am running the below C# function in both ASP.NET Web Forms and ASP.NET MVC but on MVC it exits right away without result, and on Web Forms it simply runs forever.

`var r = client.GetCandles("BTC-ETH", Bittrex.Net.Objects.TickInterval.OneDay);`

My super-simple VS project that invokes the function is: [HERE](https://drive.google.com/file/d/1YOd92Mg2ccN1I7XhJoEEHzaGVfK8ZQmp/view?usp=sharing)
It's inside Default.aspx

I have also tried the async function to no avail.
It runs well in Winform though (even with async).

Please advise.

Thanks so much!
Dave

**Comment by JKorf** [comment]
Hi, please make sure that the code is run in a separate Thread. It should work if you change your code to:
```C#
Task.Run(()=>{
    var r = client.GetCandles("BTC-ETH", Bittrex.Net.Objects.TickInterval.OneDay);
});
```

PS: Please, if you read this, immediately remove your apikey/secret from your link. With those credentials your account is open to anyone. Sadly there is no way of contacting you in a private way, so this is the only way to let you know.

**Comment by mariocaptain** [comment]
Oopss, forgot about the credentials!!!! :/
Thanks for the concern! Someone has been fast enough to use the credentials to create orders, fortunately there is not much damage, and the key is a no-withdrawal key.

Will test your code and get back shortly.

I really appreciate your help!
Dave

**Comment by AtesDANIS** [comment]
it works thanks for example (Y)
