### ISSUE TITLE
Consistently get 503 errors using BittrexSocketClient

### ISSUE THREAD

**Issue by dpyro** [JKorf/Bittrex.Net#27]
Using:
```csharp
var socketClient = new BittrexSocketClient();
socketClient.SetLogVerbosity(LogVerbosity.Debug);
await socketClient.SubscribeToAllMarketDeltaStreamAsync(...)
```
I keep getting this:
```
03:12:02:046 | Debug | Going to subscribe to all markets
03:12:02:102 | Debug | Starting connection to bittrex server
03:12:02:137 | Debug | Socket state: Disconnected -> Connecting
03:12:02:396 | Debug | Socket state: Connecting -> Disconnected
03:12:02:403 | Warning | Couldn't connect to Bittrex server, going to try CloudFlare bypass
03:12:02:449 | Debug | Socket closed
03:12:08:326 | Debug | CloudFlare cookies retrieved, retrying connection
03:12:08:332 | Debug | Socket state: Disconnected -> Connecting
03:12:08:952 | Error | Socket error: HTTP/1.1 503 Service Temporarily Unavailable
03:12:08:992 | Error | Socket error: Socket is not connected
03:12:13:534 | Debug | Socket state: Connecting -> Disconnected
03:12:13:541 | Debug | Socket closed
03:12:13:556 | Warning | Call failed: Could not connect to Bittrex server
```
This is also after I try visiting the website through a browser to trigger the CloudFlare check on the browser. `BittrexClient` meanwhile seems to work fine.

**Comment by mrboh** [comment]
Also getting the same error. Was working well 24 hours ago.

**Comment by JKorf** [comment]
Hi, I´m pretty sure the problem is on Bittrex side. Their website is also having troubles.

**Comment by dpyro** [comment]
I suspect that too. Would updating the Cloudflare bypass help in any way?

**Comment by JKorf** [comment]
Maybe, however I don't know how. Functionality on the wrapper end is unchanged, so they changed something on their end. I tried a couple of things to get it to work but no luck. 

The browser seems to be able to connect okay. When visiting bittrex.com in browser and looking at the dev console you can see the SignalR connection being made. I looked at the request parameters they use and they're the same the wrapper sends. Most notably the two cookies for passing CloudFlare: __cfduid and cf_clearance. However somehow it doesn't accept the wrapper connection, but does accept the browser connection.

I tried looking at other API users to see if they have the same problem, but can't seem to find anything. https://github.com/dparlevliet/node.bittrex.api is one that also uses the websocket, but it looks like they can connect just fine. 

So I'm a bit stuck, if anyone has any clues, please let me know. Btw, I think connection will work when Bittrex disables CloudFlare again.

**Comment by dpyro** [comment]
Can you try messing with the TLS security levels? I believe the default changed  between dotnet versions which caused me sporadic issues with the Binance .NET api (which incidentally also uses CloudFlare).

**Comment by fritz-net** [comment]
Till Commit https://github.com/JKorf/Bittrex.Net/commit/ad15da11fa51f5142b02c9b22723631cd078d891 there were 2 classes one using Websocket4Net (for .Core) and another using WebsocketSharp (for .Net) both were using non default values:

Websocket4Net:
`socket = new WebSocket(url, cookies: cookies.ToList(), customHeaderItems: headers.ToList(), receiveBufferSize: 2048, sslProtocols: SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls);
            `

WebsocketSharp:
`
            socket.SslConfiguration.EnabledSslProtocols = SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls;`

**Comment by JKorf** [comment]
I´ve managed to fix it, but I had to use the ClientWebsocket class to get it to work. This means that sadly the stream connection only works on platforms where the WebSocket protocol is available. Windows 7 doesn´t have this, so the current implementation only works on Windows 8 +.

I'll try to fix it without relying on the ClientWebsocket class, but for now it should work at least on Windows 8/ Windows 10.

**Comment by omerfaruk** [comment]
I have same issue if i open browser and go bittrex then my apps working but if i dont do this it working sometimes
