### ISSUE TITLE
Weekly & Monthly market data

### ISSUE THREAD

**Issue by mariocaptain** [JKorf/Bittrex.Net#28]
Hi JKorf,

Thanks so much for the very useful and easy to use library.
I just wanted to know if you intend to implement Weekly & Monthly data. When should we expect it?

God bless.
Dave

**Comment by JKorf** [comment]
Hi Dave, 

Thanks for your kind words. What do you expect of Weekly/Montly market data? I'm reliant on the Bittrex API as to what I can offer you. As far as I know they only have data about 24 hours (GetMarketSummaries). If they don't provide a way of accessing weekly and/or monthly data then it's not going to be available in this wrapper.

Depending on your needs you could use the GetCandles method to distill the basic highs/lows for a week or month:
```C#
    using(var client = new BittrexClient())
    {
        var candleResult = client.GetCandles("BTC-ETH", Bittrex.Net.Objects.TickInterval.OneDay);
        if (candleResult.Success)
        {
            var reversed = candleResult.Result.Reverse(); // Data is supplied early -> late, we want to process from late -> early
            var weekData = reversed.Take(7);
            var monthData = reversed.Take(30);

            Console.WriteLine($"Week high: {weekData.Max(d => d.High)}, week low: {weekData.Min(d => d.Low)}, week average volume: {weekData.Average(d => d.Volume)}");
            Console.WriteLine($"Month high: {monthData.Max(d => d.High)}, month low: {monthData.Min(d => d.Low)}, month average volume: {monthData.Average(d => d.Volume)}");
        }
    }
    Console.ReadLine();
```

**Comment by mariocaptain** [comment]
Hi JKorf,

Yes I am aware of the API, but I must have mistaken it with something else. Just double check on their API and you are absolutely right.

Thanks for the code snippet! Its very kind of you. 

Cheers,
Dave
