### ISSUE TITLE
Websocket Orderbook and All Trades

### ISSUE THREAD

**Issue by BjoernSteinmetz** [JKorf/Bittrex.Net#29]
Dear J. Korf!
Thank you for providing this library and the example code.
Could you add a template for processing of websocket data to get an in memory copy of the orderbook and the recent trades of all currencies?
Are you planning on implementing Bitfinex or Poloniex too?
Is there a way to contact you directly?
Best regards,
Björn

**Comment by JKorf** [comment]
Hi,

There currently is no way to access that data easily, sorry. The API Bittrex offers is limited, and the Websocket they provide is mainly developed for their website, not public use. The websocket allows subscription to the order book, but only to 1 currency at a time. This isn't implemented in this wrapper (yet), see #21. 

I might add Bitfinex and Poloniex aswel, but I'm currently fairly busy so don't expect it too soon.

I've added my email to my profile.
