### ISSUE TITLE
Can't connect to websocket anymore

### ISSUE THREAD

**Issue by Taats** [JKorf/Bittrex.Net#30]
Hi JKorf, 

first off, thanks for putting this library out there, it's a real time safer and the only (good) one i could find of which who supports websockets.

Speaking of websockets, since a few days i cannot connect to stream.bittrex.com using the BittrexSocketClient anymore. It keeps saying connection disconnected. Also tried running some older versions of which i knew would work but they all seem to yield the same error. So im guessing something has changed on their side, could you be so kind to look into this?

The error im getting (but the same counts for 'all markets'):
08:49:20:159 | Debug | Going to subscribe to BTC-DOGE
08:49:22:345 | Debug | Starting connection to bittrex server
08:49:22:360 | Debug | Socket state: Disconnected -> Connecting
08:49:22:520 | Debug | Socket state: Connecting -> Disconnected
08:49:22:521 | Warning | Couldn't connect to Bittrex server, going to try CloudFlare bypass
08:49:22:526 | Debug | Socket closed
08:49:30:025 | Debug | CloudFlare cookies retrieved, retrying connection
08:49:30:028 | Debug | Socket state: Disconnected -> Connecting
08:49:30:091 | Debug | Socket state: Connecting -> Disconnected
08:49:30:092 | Debug | Socket closed

**Comment by JKorf** [comment]
Hi,

I'm aware of the issue. Bittrex changed something on their end, previously the CloudFlare bypass worked fine. If you have any ideas as to what has changed or what I can try, please let me know in #27.
