### ISSUE TITLE
execute market order

### ISSUE THREAD

**Issue by rubenbryon** [JKorf/Bittrex.Net#33]
It doesn't seem to be possible to execute a market order.

**Comment by mariocaptain** [comment]
Hi rubenbryon,

I am not really sure but it seems to me that Bittrex's API doesn't support market orders. Just limit orders.
You may see [here](https://bittrex.com/home/api).

Dave

**Comment by JKorf** [comment]
Hi, as Dave mentioned, it's not part of their API, which means I can't provide it to you.
