### ISSUE TITLE
Cannot connect to websocket

### ISSUE THREAD

**Issue by tonsnoei** [JKorf/Bittrex.Net#35]
Hi,

I try to use the websocket client but it won't connect: Debug log:

03:26:20:764 | Debug | Socket state: Connecting -> Disconnected
03:26:20:766 | Warning | Couldn't connect to Bittrex server, going to try CloudFlare bypass
03:26:20:769 | Debug | Socket closed
03:26:25:926 | Debug | CloudFlare cookies retrieved, retrying connection
03:26:25:928 | Debug | Socket state: Disconnected -> Connecting
03:26:26:216 | Debug | Socket state: Connecting -> Disconnected
03:26:26:218 | Debug | Socket closed
03:26:26:245 | Warning | Call failed: Could not connect to Bittrex server

I could login to Bittrex via the browser.

Hope you can help me out.

Kind regards,
Ton Snoei

**Comment by mmartain** [comment]
Yes, i have this too. They might have changed something...

**Comment by badokun** [comment]
Same for me. I tried connecting from various IPs too.

**Comment by JKorf** [comment]
I´ve just pushed a new version, see #27.

**Comment by badokun** [comment]
Sorry to be the bearer of bad news. Seems the nuget package is busted. At least for 4.6.1

PM> install-package Bittrex.Net


Attempting to gather dependency information for package 'Bittrex.Net.1.3.3' with respect to project 'ConsoleApp1', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 1.28 min
Attempting to resolve dependencies for package 'Bittrex.Net.1.3.3' with DependencyBehavior 'Lowest'
install-package : Unable to find a version of 'CloudFlareUtilities' that is compatible with 'Bittrex.Net 1.3.3 constraint: CloudFlareUtilities (>= 0.5.0-alpha)'.
At line:1 char:1
+ install-package Bittrex.Net
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:01:17.3834310

**Comment by badokun** [comment]
Ah never mind. Had to completely remove the nuget package and reinstall. Works now
