### ISSUE TITLE
Fix Websocket connection for platforms without Websocket protocol support

### ISSUE THREAD

**Issue by JKorf** [JKorf/Bittrex.Net#36]

**Comment by fritz-net** [comment]
on win7 i get the following error when using longpolling
```
01:48:10:648 | Debug | Going to subscribe to BTC-ETH
01:48:10:660 | Debug | Starting connection to bittrex server
01:48:10:726 | Debug | Socket state: Disconnected -> Connecting
01:48:11:676 | Debug | Socket state: Connecting -> Disconnected
01:48:11:687 | Debug | Socket closed
01:48:11:716 | Warning | Couldn't connect to Bittrex server, going to try CloudF
lare bypass
01:48:17:272 | Debug | CloudFlare cookies retrieved, retrying connection
01:48:17:272 | Debug | Socket state: Disconnected -> Connecting
01:48:17:891 | Error | Socket error: StatusCode: 400, ReasonPhrase: 'Bad Request
', Version: 1.1, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
{
  Cache-Control: no-cache
  Connection: keep-alive
  Date: Wed, 03 Jan 2018 00:48:08 GMT
  Pragma: no-cache
  Transfer-Encoding: chunked
  Server: cloudflare-nginx
  X-Content-Type-Options: nosniff
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=15768000
  X-XSS-Protection: 1; mode=block
  X-Download-Options: noopen
  CF-RAY: 3d71f362efb48cb8-VIE
  Content-Type: text/html
  Expires: -1
}
01:48:17:951 | Debug | Socket state: Connecting -> Disconnected
01:48:17:952 | Debug | Socket closed
01:48:17:972 | Warning | Call failed: Could not connect to Bittrex server
```

this is the request done by the lib (which looks fine to me, but i don't know if bittrex supports long polling)
```
POST https://socket.bittrex.com/signalr/connect?clientProtocol=1.4&transport=longPolling&connectionData=[%7B%22Name%22:%22coreHub%22%7D]&connectionToken=6iiSnLzyax4iVZOQMlSeN1eniN7xIcVEHbAUAjlmqx3hJfnR2A%2FcX4L0u%2BpPzCH%2Bm%2BhdBaMfgVZIxcpI4iGVZhundgsTpAQguiJf3nSoH9qAlwDJ HTTP/1.1
Connection: Keep-Alive
Content-Type: text/plain; charset=utf-8
Cookie: __cfduid=d8089d6bd9d83fa74c451d26223724e1a1514940482; cf_clearance=586750fff54b89a686b45c90f304547059be2c0f-1514940487-10800
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 OPR/48.0.2685.52
Content-Length: 0
Host: socket.bittrex.com
```

**Comment by mmartain** [comment]
06:14:00:269 | Debug | Going to subscribe to all markets
06:14:00:283 | Debug | Starting connection to bittrex server
06:14:00:329 | Debug | Socket state: Disconnected -> Connecting
06:14:00:789 | Debug | Socket state: Connecting -> Disconnected
06:14:00:792 | Debug | Socket closed
06:14:00:806 | Warning | Couldn't connect to Bittrex server, going to try CloudFlare bypass
06:14:06:639 | Debug | CloudFlare cookies retrieved, retrying connection
06:14:06:639 | Debug | Socket state: Disconnected -> Connecting
06:14:07:164 | Error | Socket error: StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  Pragma: no-cache
  X-Content-Type-Options: nosniff
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=15768000
  X-XSS-Protection: 1; mode=block
  X-Download-Options: noopen
  CF-RAY: 3d7797b66b7c4445-BRU
  Cache-Control: no-cache
  Date: Wed, 03 Jan 2018 17:14:07 GMT
  Server: cloudflare-nginx
  Content-Type: text/html
  Expires: -1
}
06:14:08:084 | Debug | Socket state: Connecting -> Connected

I get this on Windows 10 with latest updates... Strange..

**Comment by fritz-net** [comment]
Could you use fiddler to check if your windows uses LongPolling as well? (this is visible in the requested url)

**Comment by JKorf** [comment]
I'm pretty sure Bittrex disabled LongPolling, as it also doesn't support ServerSentEvents anymore. I've seen the 400 bad request message appear as well, but it doesn't seem to have any implication on whether it is going to work or not. 

I've pushed an update which should work on all platforms again.
