### ISSUE TITLE
Exception thrown in GetBalance if no wallet address is claimed

### ISSUE THREAD

**Issue by rutgervanwilligen** [JKorf/Bittrex.Net#37]
I've stumbled upon a deserialization error in the `GetBalance(string)` call. The problem arises when getting the balance for a specific currency for which you haven't claimed a wallet yet on your Bittrex account. The (successful) JSON response from Bittrex is as follows:

```
{
	"success": true,
	"message": "",
	"result": {
		"Currency": "LTC",
		"Balance": null,
		"Available": null,
		"Pending": null,
		"CryptoAddress": null
	}
}
```

Deserialization fails because the `null` values of `Balance`, `Available` and `Pending` cannot be deserialized into `decimal`s; the full error message is `"Error parsing the returned data to object.\r\nMessage: Error converting value {null} to type 'System.Decimal'. Path 'result.Balance', line 1, position 70.. Received data: {\"success\":true,\"message\":\"\",\"result\":{\"Currency\":\"LTC\",\"Balance\":null,\"Available\":null,\"Pending\":null,\"CryptoAddress\":null}}"`.

One could reason that throwing an exception is a good idea here (because the requested wallet does not exist for the specified currency), but I would argue that that should be part of application logic instead (as in this JSON response, `success` is set to `true`). I would therefore change the data types of the `BittrexBalance` fields to nullable decimals instead.

**Comment by JKorf** [comment]
Agreed, this is fixed in the latest version.

**Comment by rutgervanwilligen** [comment]
Cheers!
