### ISSUE TITLE
Cant Use .Last for checking bitcoin / altcoin price 

### ISSUE THREAD

**Issue by RedCreeperMC** [JKorf/Bittrex.Net#4]
cant use .Last, tested in xamarin, console application .net 4.5 / mono, version 0.0.3,
please fix this

**Comment by JKorf** [comment]
Sorry to hear that. What call do you mean? 
Can you provide a sample of what you're trying to do?

**Comment by RedCreeperMC** [comment]
`using System;
using Bittrex.Net;

namespace miner
{
	public class start_miner_class
	{
		public static void start_miner()
		{
			try
			{
				using (var client = new BittrexClient())
				{
					var price_result = client.GetTicker("BTC-ETH");
					if (price_result.Success)
					{
						Console.WriteLine($"BTC-ETH price: {price_result.Last}");
					}
				}
			}`

that price_result.Last    isn't working it says : does not contain a definition for "Last" even when I added the using namespace for System.linq

**Comment by JKorf** [comment]
I see, I think you need to change 
Console.WriteLine($"BTC-ETH price: {price_result.Last}");
to
Console.WriteLine($"BTC-ETH price: {price_result.Result.Last}");

**Comment by JKorf** [comment]
I see that is an error in the documentation, I've fixed it now. Sorry for the inconvenience!
