### ISSUE TITLE
Cannot install the package with .Net 4.6.1

### ISSUE THREAD

**Issue by juanonsoftware** [JKorf/Bittrex.Net#40]
When install the package into my project under VS 2015, the below error happens:

Unable to find a version of 'CloudFlareUtilities' that is compatible with 'Bittrex.Net 1.3.4 constraint: CloudFlareUtilities (>= 0.5.0-alpha)'.

**Comment by JKorf** [comment]
See #41, it works when you first manually install CloudFlareUtilities 0.5.0-alpha and then Bittrex.net
