### ISSUE TITLE
Fix cloudflare utilities packages

### ISSUE THREAD

**Issue by JKorf** [JKorf/Bittrex.Net#41]
CloudFlareUtilities package can't automatically install for some reason. Does work when manually installing and installing this wrapper after. Comes with multiple dependencies though because it is a .netstandard library.

Check for fix/alternative.

**Comment by ppisljar** [comment]
same issue, can't install cloudflareutilities on .net 4.5 (visual studio 2012)
by the way ... which .net framework is required for bittrex.net to work ? any chance i'll be able to use this on .net 4.5 ?

**Comment by ppisljar** [comment]
i tried converting my project to vs 2017, still the same problem, cloudflareutilities can't be installed (target framework 4.5)

**Comment by fritz-net** [comment]
For me it works with .Net 4.5.2 and .Net Core2.0 properly. travis-ci tests building this with .net Core2.0 too.
I use Visual Studio 2017 Pro with this repo checked out in a separate folder and added to my solution. CloudFlareUtilities is checked out by NuGet without problems.

I hope this helps you getting this to work. (better without nuget than not at all)

**Comment by ppisljar** [comment]
thanks, i got it working!

however only async methods work, the non-async will just wait for ever (won't even time out, i wanted 30 minutes, no response) ... anyone has idea why that would be ?

**Comment by fritz-net** [comment]
@ppisljar 
Does this https://github.com/JKorf/Bittrex.Net/pull/45 fixed your problem?

**Comment by JKorf** [comment]
Just tested, installing works fine now, maybe because of upgrade to CloudFlareUtilities v1.0. Can't do much about the amount of packages that come with it when using Bittrex.Net from a .Net framework application.
