### ISSUE TITLE
Orderbook with websocket

### ISSUE THREAD

**Issue by passa1248** [JKorf/Bittrex.Net#44]
Can we take orderbooks using QueryExchangeState like a browser?
Thanks in advance!

**Comment by fritz-net** [comment]
This is possible by using my merge request https://github.com/JKorf/Bittrex.Net/pull/42
However I see no benefit for this using websockets since you will only get one result, no refreshes

`SubscribeToExchangeDeltas` will give you regular updates

**Comment by passa1248** [comment]
Thanks!

**Comment by passa1248** [comment]
why if i do
` ws.HubProxy.Invoke("SubscribeToExchangeDeltas","BTC-LTC"); `
work but this:
` ws.HubProxy.Invoke("QueryExchangeState","BTC-LTC");`

not work?
Thanks in advance!

**Comment by fritz-net** [comment]
What do you mean with not working? `QueryExchangeState` only gives one result, after this you will get empty json objects `{}`
Have you checked your network communication with something like fiddler?

**Comment by passa1248** [comment]
with:
`ws.Received += Connection_Received();`
and
```
 private void Connection_Received(string data)
        {
          Console.WriteLine(data);       
        }
```
I show all data received by websocket but when I call 
`ws.HubProxy.Invoke("QueryExchangeState","BTC-LTC");`
I not see anything :( ,  is it normal?

**Comment by fritz-net** [comment]
For me it works perfectly as you can see in the image and I'm doing nearly the same (see my fork)
![image](https://user-images.githubusercontent.com/2499282/34672144-940cbb20-f47d-11e7-98ce-ee802aa3294f.png)
have you checked your network traffic? does it also stops? or is only the callback not working?

**Comment by passa1248** [comment]
Sorry I'm not able to see websocket packages with Fiddler 4.6.1 :(

![screen](https://user-images.githubusercontent.com/19681865/34687906-85038cca-f4b0-11e7-907a-d69ab0fbe7b7.png)

**Comment by fritz-net** [comment]
https://github.com/JKorf/Bittrex.Net/pull/42/files/9dd6237e612eddde9db456adfcee1c146ee5a735#diff-6c648fe90e6e33d0f6fd954ae7e92fee

use the code to proxy the websocket trafic to fiddler

I habe proxy codes for Websocket4net and WebsocketSharp there

**Comment by quangtho2910** [comment]
Hi @fritz-net 
Could you please teach me where SubscribeToExchangeDeltas method? Because i did not see any method you mentioned in BittrexSocketClient class.

**Comment by fritz-net** [comment]
@quangtho2910, this is how I use it. In this example I iterate over all Fills. Buy and Sell orderbook entries are also available.

I want to mention that you have to use my Fork if you want to use this feature now since it's not merged yet cause I have to fix some things first.

```
            String ProductName = product1.ToString() + "-" + product2.ToString();
            logger.InfoFormat("subscribe to {0}", ProductName);
            
            subcribtions.Add(socketClient.SubscribeToSubscribeToExchangeDeltas(ProductName, StreamData =>
            {
                // don't use parallel to keep right timing order
                foreach (BittrexOrderBookFill data in StreamData.Fills)
                {
                    var trade = new Trade();
                    trade.Quantity = data.Quantity;
                    trade.Rate = data.Rate;
                    trade.OrderType = data.OrderType;
                    trade.TimeStamp = data.TimeStamp;

                    trade.MarketName = StreamData.MarketName;

                    clb(trade);
                }

                
            }));
```

**Comment by cooljbg** [comment]
for QueryExchangeState
var initOrders = ws.HubProxy.Invoke<dynamic>("QueryExchangeState","BTC-LTC");

**Comment by fritz-net** [comment]
@cooljbg, I also added this to my branch + merge request:

```
            // initial
            socketClient.QueryExchangeState(ProductName, initialData =>
            {
                // Handle data
                logger.Debug(initialData.ToString());
            });
```

**Comment by quangtho2910** [comment]
@fritz-net 
Sorry but what is "subcribtions" variable in your code?

**Comment by passa1248** [comment]
@cooljbg ok thanks, I was waiting result on Connection_Received callback function but this work

`  _ws.HubProxy.Invoke<dynamic>("QueryExchangeState", "BTC-LTC").ContinueWith(task =>
                      {
                         Console.WriteLine(task .Result);
                      });`

**Comment by fritz-net** [comment]
@quangtho2910, yeah I use this list to clean up the subscriptions afterwards.

**Comment by quangtho2910** [comment]
I got it. Thank you so much @fritz-net! Waiting for new release version!

**Comment by JKorf** [comment]
New version is released :)

**Comment by quangtho2910** [comment]
Hi @fritz-net,
Can we subscribe all exchange deltas like subscribe all market delta stream? I would like to get all orders book from all markets. 
Should i loop all markets then subscribe one by one?

**Comment by fritz-net** [comment]
@quangtho2910 I don't know if there API has a method like this. Is there an overview of all orderbooks on bittrex? I think the have nearly 300 markets ... maybe it is not the best idea to get them all over one single stream, especially high volume markets
I haven't tried anything. Looping should be possible

**Comment by JKorf** [comment]
The API doesn't support this. You can loop over each market as @fritz-net suggested, but that's going to to take some time to do, and it would leave you with a lot of data.

**Comment by fritz-net** [comment]
@quangtho2910 tell us if you get blocked (on ip basis, ...) when you subscribe to all markets or if the API doesn't care at all

**Comment by JKorf** [comment]
I was curious as to whether this was possible so I tried it, it seems to be possible, but I'm not sure you can process the data that quickly. Here is a screenshot of the amount of data:

![image](https://user-images.githubusercontent.com/8448172/34989739-f3de02e2-fac3-11e7-9fed-19acff162854.png)

It averages 100-200 update calls per second. The total items is the amount of entries in the Buys/Sells/Fills fields combined. I've only had it running for a couple off minutes.

**Comment by quangtho2910** [comment]
Thank you @JKorf and @fritz-net 
Let me try to get all data. The best way is get old market history but bittrex did not provide websocket for that one. And they limit to 100 histories per request. It would be nice if they release market history using websocket in the next version!
