### ISSUE TITLE
Help with vb format

### ISSUE THREAD

**Issue by Cjay93** [JKorf/Bittrex.Net#49]
Hi just wondering if anyone could convert this to visual basic, im having a hard time with the syntax format.

using(var socketClient = new BittrexSocketClient())
{
	var subcribtionSuccess = socketClient.SubscribeToMarketDelta("BTC-ETH", data =>
	{
		// Handle data
	});
	
	socketClient.UnsubscribeFromStream(subcribtionSuccess.Result); // Unsubscribes a single sub
        socketClient.UnsubscribeAllStreams(); // Unsubscribes all subs on this client 
}

Thank you

**Comment by JKorf** [comment]
Hi, I've just created a new Nuget package with the order book functionality provided by @fritz-net. Do you still need help with this or can you use that?

**Comment by Cjay93** [comment]
That does help alot, but still struggling to write that ocketClient.SubscribeToMarketDelta("BTC-ETH", data =>
{ in vb.
It weird syntax for converters to convert it seems.
Thanks so much sir

**Comment by JKorf** [comment]
I'm don't program VB.Net myself, but isn't it something like:
````
socketClient.SubscribeToMarketDelta("BTC-ETH", Function(data as BittrexMarketSummary)
                                                      // Do something with data
                                               End Function)
````

Based on https://www.dotnetperls.com/lambda-vbnet

**Comment by Cjay93** [comment]
Thanks so much, appreciate it.
