### ISSUE TITLE
error 6000 INVALID_PERMISSION

### ISSUE THREAD

**Issue by projektai** [JKorf/Bittrex.Net#51]
Hi, i get 6000 INVALID_PERMISSION error when i call GetBalance method. 

_var client = new BittrexClient(bittrexApiKey, bittrexApiSecret);
using (client)
{
client.SetApiCredentials(bittrexApiKey, bittrexApiSecret);
 var quantity = client.GetBalance("BTC");
}_

**Comment by CssHammer** [comment]
Does your API key have Read Info permission?

**Comment by projektai** [comment]
where i can find this settings?

**Comment by JKorf** [comment]
In https://bittrex.com/Manage#sectionApi make sure the Read Info switch is turned on to allow the application to read data from your account.

**Comment by JKorf** [comment]
Can I assume this issue is resolved?

**Comment by projektai** [comment]
Yes, thanks.
