### ISSUE TITLE
Add SubscribeToUserDeltas websocket

### ISSUE THREAD

**Issue by passa1248** [JKorf/Bittrex.Net#52]
Hi all!
Can you add SubscribeToUserDeltas method  with websocket?
Thanks in advance!

**Comment by JKorf** [comment]
Hi, I haven't looked into this, but what is that method supposed to do? I think it might be hard because it is user specific and it probably uses cookies or data from the website login or something

**Comment by passa1248** [comment]
It's very useful if you not want do GetOpenOrder loop after PlaceOrder call for check if order was filled or not.

**Comment by JKorf** [comment]
I agree it's useful, but I don't think I can implement this in any reasonable way. As I expected the call needs a cookie which you get by logging in on the website. There is some discussion on it here:
https://github.com/n0mad01/node.bittrex.api/issues/38
I won't put any effort into this for now, hopefully Bittrex will expand their API sometime soon.
