### ISSUE TITLE
Bittrex websocket connection

### ISSUE THREAD

**Issue by IshFx** [JKorf/Bittrex.Net#54]
Hello,

I'm trying to get live data using the bittrex socket client but i keep getting errors.
The client doesn't connect to the remote host.

> 11:58:37:530 | Debug | Going to subscribe to BTC-ETH
> 
> 11:58:37:596 | Debug | Starting connection to bittrex server
> 11:58:37:770 | Debug | Socket state: Disconnected -> Connecting
> 11:58:38:536 | Debug | Socket state: Connecting -> Disconnected
> 11:58:38:554 | Debug | Socket closed
> 
> 11:58:38:556 | Warning | Couldn't connect to Bittrex server, going to try CloudFlare bypass
> 11:58:38:699 | Debug | CloudFlare cookies retrieved, retrying connection
> 11:58:38:699 | Debug | Socket state: Disconnected -> Connecting
> 11:58:38:798 | Debug | Socket state: Connecting -> Disconnected
> 11:58:38:799 | Debug | Socket closed
> 11:58:38:807 | Warning | Call failed: Could not connect to Bittrex server

I installed this wrapper (v1.3.4) using nuget.

Do you have an idea on why it cant connect ?

Thanks in advance.

**Comment by JKorf** [comment]
Hi, if you try the latest version (1.3.7) it should work again. There was a problem with one of the dependencies.

**Comment by IshFx** [comment]
Thank you very much. It works indeed better !

However i keep getting an 503 error.

> 01:51:05:692 | Debug | Going to subscribe to BTC-ETH
> 01:51:05:739 | Debug | Starting connection to bittrex server
> 01:51:06:119 | Debug | Socket state: Disconnected -> Connecting
> 01:51:07:236 | Debug | Socket state: Connecting -> Disconnected
> 01:51:07:251 | Debug | Socket closed
> 01:51:07:374 | Debug | System.AggregateException: One or more errors occurred. (StatusCode: 503, ReasonPhrase: 'Service Temporarily Unavailable', Version: 1.1, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
> {
>   Cache-Control: no-cache
>   Connection: close
>   Date: Wed, 17 Jan 2018 12:51:07 GMT
>   Transfer-Encoding: chunked
>   Server: cloudflare
>   Set-Cookie: __cfduid=d3b36d62bb0312522ba0220d54399efa11516193467; expires=Thu, 17-Jan-19 12:51:07 GMT; path=/; domain=.bittrex.com; HttpOnly
>   X-Frame-Options: SAMEORIGIN
>   CF-RAY: 3de971b1ab323470-LHR
>   Content-Type: text/html; charset=UTF-8
> }) ---> Microsoft.AspNet.SignalR.Client.HttpClientException: StatusCode: 503, ReasonPhrase: 'Service Temporarily Unavailable', Version: 1.1, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
> {
>   Cache-Control: no-cache
>   Connection: close
>   Date: Wed, 17 Jan 2018 12:51:07 GMT
>   Transfer-Encoding: chunked
>   Server: cloudflare
>   Set-Cookie: __cfduid=d3b36d62bb0312522ba0220d54399efa11516193467; expires=Thu, 17-Jan-19 12:51:07 GMT; path=/; domain=.bittrex.com; HttpOnly
>   X-Frame-Options: SAMEORIGIN
>   CF-RAY: 3de971b1ab323470-LHR
>   Content-Type: text/html; charset=UTF-8
> }
>    at Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.<>c__DisplayClass5_0.<Get>b__1(HttpResponseMessage responseMessage)
>    at Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass3_0.<RunTask>b__0(Task`1 t)
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at Bittrex.Net.BittrexSocketClient.TryStart()
> ---> (Inner Exception #0) Microsoft.AspNet.SignalR.Client.HttpClientException: StatusCode: 503, ReasonPhrase: 'Service Temporarily Unavailable', Version: 1.1, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
> {
>   Cache-Control: no-cache
>   Connection: close
>   Date: Wed, 17 Jan 2018 12:51:07 GMT
>   Transfer-Encoding: chunked
>   Server: cloudflare
>   Set-Cookie: __cfduid=d3b36d62bb0312522ba0220d54399efa11516193467; expires=Thu, 17-Jan-19 12:51:07 GMT; path=/; domain=.bittrex.com; HttpOnly
>   X-Frame-Options: SAMEORIGIN
>   CF-RAY: 3de971b1ab323470-LHR
>   Content-Type: text/html; charset=UTF-8
> }
>    at Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.<>c__DisplayClass5_0.<Get>b__1(HttpResponseMessage responseMessage)
>    at Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass3_0.<RunTask>b__0(Task`1 t)<---
> 
> 01:51:07:375 | Warning | Couldn't connect to Bittrex server, going to try CloudFlare bypass
> 01:51:13:231 | Debug | CloudFlare cookies retrieved, retrying connection
> 01:51:13:231 | Debug | Socket state: Disconnected -> Connecting
> 01:51:28:683 | Debug | Socket state: Connecting -> Disconnected
> 01:51:28:684 | Debug | Socket closed
> 01:51:28:688 | Debug | System.AggregateException: One or more errors occurred. (Transport timed out trying to connect) ---> System.TimeoutException: Transport timed out trying to connect
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at Bittrex.Net.BittrexSocketClient.TryStart()
> ---> (Inner Exception #0) System.TimeoutException: Transport timed out trying to connect<---
> 
> 01:51:28:696 | Warning | Call failed: Could not connect to Bittrex server

Thats odd because my browser has a 200 response : 
![img](https://user-images.githubusercontent.com/23222270/35043858-742600a6-fb8e-11e7-9d36-ea78392674a7.PNG)

**Comment by JKorf** [comment]
That is odd.. It's working for me locally. What version of .Net are you using?

**Comment by IshFx** [comment]
Im using netstandard 2.0.

**Comment by JKorf** [comment]
I can't reproduce your problem. What is the code you are using to connect? Could it be that the call is blocked by your network or something?

**Comment by IshFx** [comment]
I think its my company's firewall, i'll let you know when i get home.
Thanks for the help !

**Comment by fritz-net** [comment]
Timeout sounds like there are firewall issues, however i though the websocket uses port 443 ... maybe there is also a proxy in between intercepting stuff ...

If it helps you, you could use a proxy for the websocket stuff ;)

**Comment by IshFx** [comment]
Indeed ! It works on my personal computer. It was the firewall.

However it has to retry the connection because the first request returns a 503 error, but after getting cloudflare cookies, it works great. It may be better to get the cookies the first time to avoid this error. I can PR this if requested.

Thank you anyway for your help, i can now close this issue.

**Comment by JKorf** [comment]
Bittrex used to not have Cloudflare protection turned on by default, so it made sense to first try without retrieving cookies. For the last 2 months or so though they've had it turned on, so I guess by now it might be better to just retrieve the cookies at first try. The first try to connect without cookies normally fails pretty fast though (< 2 seconds), while retrieving the cookies takes some time (+- 10s), so for performance it wouldn't help that much.

**Comment by IshFx** [comment]
True !

About that timeout, i found out that it wasn't the firewall. All i had to do is set my company's proxy ! Everything works great right now.

**Comment by JKorf** [comment]
Great to hear :)

**Comment by fritz-net** [comment]
@IshFx, how did you set the proxy? I'm just wondering why you got the 503 without timeout and when doing the websocket stuff you get the timeout

**Comment by IshFx** [comment]
@fritz-net The 503 error is due to the absence of the cloudflare cookies, that's why i said its better to grab them at the beginning.

To set a proxy, the library provides a Method, its signature is 
`void SetProxy(String Host, int Port)`

Or you can set `ProxyHost` and `ProxyPort` directly.

**Comment by fritz-net** [comment]
@IshFx, i was just wondering why the 503 got through ;) because if you can't access the internet without the proxy you can't get an 503 for missing cookies or get the right cookies from cloudflare since as far as I know the Proxy method only works for the websocket itself

**Comment by IshFx** [comment]
@fritz-net Oh sorry i didn't understand the first time.
You're right, it's odd, and i don't get it either.

Does the HttpClient class use the default system proxy ? if it's the case, then here is your answer.
