### ISSUE TITLE
Issues in Request.Cs

### ISSUE THREAD

**Issue by mikecheckyaself** [JKorf/Bittrex.Net#55]
I seem to be getting an issue in the Request.cs class at the bold points:

 public class Request : **IRequest**
    {
        public readonly WebRequest request;

        private Request(WebRequest request)
        {
             this.request = request;
        }
public WebHeaderCollection Headers
        {
            **get => request.Headers;
            set => request.Headers = value;**
        }
        public string Method
        {
            **get => request.Method;
            set => request.Method = value;**
        }

I don't think that the Headers object from IRequest is being properly implemented here. Sorry if this is a noob issue.

**Comment by JKorf** [comment]
Hi,

What is the exact problem you're having? You say you have an issue, are you getting an exception of some sort?

**Comment by JKorf** [comment]
Have you managed to figure it out or do you still need help?

**Comment by JKorf** [comment]
I'll assume you've figured it out. If not, please let me know
