### ISSUE TITLE
BittrexSocketClient doesn't work with DotNetCore2

### ISSUE THREAD

**Issue by JKorf** [JKorf/Bittrex.Net#6]
Doesn't connect, works with .Net 4.6.

**Comment by JKorf** [comment]
I've tested and resolved the issue for DotNetCore2, the SignalR client library uses different User-Agent strings for different DotNet versions. This broke the CloudFlare authentication because the user-agents from initial authorization and the socket connections need to match.

I've also added support for NetStandard2.0 in the new release, so everything should work out of the box in DotNetCore2 aswel :)

**Comment by wklm** [comment]
Awesome, many thanks!
