### ISSUE TITLE
Issue with Windows Server

### ISSUE THREAD

**Issue by wasimjee** [JKorf/Bittrex.Net#60]
Hi,

After having subscription i am unable to recieved data in Windows Server 2012 and windows server 2016.

but on my local PC in Windows 10 its working fine.

i have copied all the dlls, but not getting data.

**Comment by JKorf** [comment]
Hi, 

Could you set the logging verbosity to Debug and share what the logging says when connecting?

**Comment by wasimjee** [comment]
I am using 

`    socketClient.SubscribeToExchangeDeltasAsync("BTC-LTC", data =>
     {
     GetMarketdata(data);
     });`

and these for catching

`    private void GetMarketdata(BittrexStreamExchangeState data)
     {
      // processing
     }`


i am getting the data and can process those in my local pc, and after compiling it i can again get those data and can process.

but when i transfer that exe and all its dll, i am not recieving the data.

i feel its the issue with 

Microsoft.AspNet.SignalR.Client.dll

System.Runtime.InteropServices.RuntimeInformation.dll

i am not sure.

i am using Windows server 2012 and windows server 2016

and my development PC is Windows 10 64bit
and using 4.2.2 framework

**Comment by JKorf** [comment]
Its hard for me to say anything about this since I don't have a Windows server installation I can use.

Can you try to run this ConsoleApplication on the Windows server and reply with the logging that was produced in the C:/logging.txt file?

````C#
        static void Main()
        {
            using (var streamWriter = new StreamWriter("C:/logging.txt"))
            {
                streamWriter.AutoFlush = true;
                BittrexSocketClient s = new BittrexSocketClient();
                s.SetLogOutput(streamWriter);
                s.SetLogVerbosity(LogVerbosity.Debug);

                s.SubscribeToExchangeDeltas("BTC-LTC", data =>
                {
                    streamWriter.WriteLine("Data received");
                });

                Thread.Sleep(60 * 1000);
            }
        }
````

**Comment by wasimjee** [comment]
ok i am trying it

**Comment by wasimjee** [comment]
> 04:26:25:780 | Debug | Starting connection to bittrex server
> 04:26:25:811 | Debug | Socket state: Disconnected -> Connecting
> 04:26:26:014 | Debug | Socket state: Connecting -> Disconnected
> 04:26:26:014 | Debug | Socket closed
> 04:26:26:030 | Debug | System.AggregateException: One or more errors occurred. ---> Microsoft.AspNet.SignalR.Client.HttpClientException: StatusCode: 503, ReasonPhrase: 'Service Temporarily Unavailable', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
> {
>   Transfer-Encoding: chunked
>   Connection: close
>   X-Frame-Options: SAMEORIGIN
>   Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
>   CF-RAY: 3e975e158d3115d7-FRA
>   Cache-Control: no-cache
>   Date: Wed, 07 Feb 2018 15:26:26 GMT
>   Set-Cookie: __cfduid=d6a698488baa80edd36beb0a5c3f419391518017186; expires=Thu, 07-Feb-19 15:26:26 GMT; path=/; domain=.bittrex.com; HttpOnly
>   Server: cloudflare
>   Content-Type: text/html; charset=UTF-8
> }
>    at Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.<>c__DisplayClass5_0.<Get>b__1(HttpResponseMessage responseMessage)
>    at Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass31_0`2.<Then>b__0(Task`1 t)
>    at Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass3_0.<RunTask>b__0(Task`1 t)
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at Bittrex.Net.BittrexSocketClient.TryStart()
> ---> (Inner Exception #0) Microsoft.AspNet.SignalR.Client.HttpClientException: StatusCode: 503, ReasonPhrase: 'Service Temporarily Unavailable', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
> {
>   Transfer-Encoding: chunked
>   Connection: close
>   X-Frame-Options: SAMEORIGIN
>   Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
>   CF-RAY: 3e975e158d3115d7-FRA
>   Cache-Control: no-cache
>   Date: Wed, 07 Feb 2018 15:26:26 GMT
>   Set-Cookie: __cfduid=d6a698488baa80edd36beb0a5c3f419391518017186; expires=Thu, 07-Feb-19 15:26:26 GMT; path=/; domain=.bittrex.com; HttpOnly
>   Server: cloudflare
>   Content-Type: text/html; charset=UTF-8
> }
>    at Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.<>c__DisplayClass5_0.<Get>b__1(HttpResponseMessage responseMessage)
>    at Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass31_0`2.<Then>b__0(Task`1 t)
>    at Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass3_0.<RunTask>b__0(Task`1 t)<---
> 
> 04:26:26:030 | Warning | Couldn't connect to Bittrex server, going to try CloudFlare bypass
> 04:26:31:451 | Debug | CloudFlare cookies retrieved, retrying connection
> 04:26:31:451 | Debug | Socket state: Disconnected -> Connecting
> 04:26:33:186 | Debug | Socket state: Connecting -> Connected
> 04:26:33:201 | Debug | Going to subscribe to ExchangeDeltas of BTC-LTC
> Data received
> Data received
> Data received


its working with console. but not with software.
even i compiled your example software , but its too not working

your example software : WinformsClient

**Comment by JKorf** [comment]
What version of the library are you running? If you're running an older version it might be that it doesn't work on every platfrom.

**Comment by wasimjee** [comment]
i am using the latest, as its working on console but not with winform

`    public partial class Form1 : Form
    {
        private BittrexSocketClient socketClient;
        
        public Form1()
        {
            InitializeComponent();

            Load += LoadDone;
        }

        private void LoadDone(object sender, EventArgs e)
        {
            Task.Run(() =>
            {
                using (var streamWriter = new StreamWriter("C:/logging1.txt"))
                {
                    streamWriter.AutoFlush = true;
                    socketClient = new BittrexSocketClient();
                    socketClient.SetLogOutput(streamWriter);
                    socketClient.SetLogVerbosity(LogVerbosity.Debug);
                    socketClient.SubscribeToMarketDeltaStream("BTC-LTC", data =>
                    {
                        streamWriter.WriteLine(data.Last);
                        UpdateLastPrice(data.Last);
                    });
                    
                }
                
                
            });

            //Task.Run(() =>
            //{
            //    using (var client = new BittrexClient())
            //    {
            //        var result = client.GetMarketSummary("BTC-ETH");
            //        UpdateLastPrice(result.Result.Last);
            //        label2.Invoke(new Action(() => { label2.Text = "BTC-ETH Volume: " + result.Result.Volume; }));
            //    }
            //});
        }

        private void UpdateLastPrice(decimal price)
        {
            label1.Invoke(new Action(() => { label1.Text = "BTC-ETH Last price: " + price; }));
        }
    }`

using this code

**Comment by wasimjee** [comment]
The issue was with other references.

now able to run on Server 2012 and Server 2016.

Thanks @JKorf  for giving time.
