### ISSUE TITLE
Support V2 of API

### ISSUE THREAD

**Issue by LadislavBohm** [JKorf/Bittrex.Net#61]
Hello,
at first I would like to thank you for the work on this library, it's the best C# bittrex library available!
One think I'm missing is support for V2 of Bittrex API. I know it's in beta, but it offers some nice additional features, like setting proper stoploss order.
As a workaround it would be nice for IBittrexClient interface to support sending raw IRequest that could be modified accoring to new version of the API. This way I could use the client as it is and if I need to call new endpoint, I would just create custom IRequest and send it through the client (using same authentication, logging, rate limiter etc.).
Another way would be (not very nice I think) to mark BittrexClient methods as virtual, so I can inherit and override those to my usage (however different parameters are needed, so it's not great solution).

Thanks for considering this.

**Comment by JKorf** [comment]
Hi,
Thanks for the kind words. 
What I would suggest is to create a subclass of the BittrexClient and adding a function to do something custom. The ExecuteRequest method is protected, so you can use that to make the actually request, which will handle the authentication. This way you can specify your own params and return model. You can also use the GetUrl method which will construct an Uri for you, or provide your own Uri:
````C#
    public class BittrexClientCustom: BittrexClient
    {
        public async Task<BittrexApiResult<object>> Test(string param)
        {
            var url = GetUrl("account/getbalances", "api", "1.1"); // Use helper
            url = new Uri("https://www.bittrex.com/someOtherEndpoint"); // Or just contruct your own uri
            var shouldUseAuthentication = true; // Whether the library should add credentials based on apikey/secret to the request (needed for private endpoints)

            return await ExecuteRequest<object>(url, shouldUseAuthentication); // The type parameter is the model you expect back
        }
    }
````

**Comment by LadislavBohm** [comment]
Thanks for the suggestion I totally missed that this method is protected. That serves as very nice solution to extending client for new API calls.
I think since V2 is beta and probably will be for quite some time I'll close this issue. In the future if you start working on the new API version and need some help implementing it, I can create some PR's.
