### ISSUE TITLE
BittrexExchangeState on QueryExchangeStateAsync has MarketName = null

### ISSUE THREAD

**Issue by daerhiel** [JKorf/Bittrex.Net#62]
Hi,
I have a problem when subscribing to QueryExchangeStateAsync. I register to one market, basically, BTC-ZCL, and the first callback event on this method returns data but has null MarketName.

**Comment by JKorf** [comment]
Hi, Bittrex actaully returns the field like that. It always sends a field marketName with value null. I can manually add the market name in the callback though. Will be in the next release.

**Comment by daerhiel** [comment]
Cool, that would be great, than you! :)

**Comment by JKorf** [comment]
Should be fixed in the latest version
