### ISSUE TITLE
Timestamp source on BittrexSocketClient

### ISSUE THREAD

**Issue by daerhiel** [JKorf/Bittrex.Net#64]
Hi there..
Wanted to ask, what is the source of timestamps on socket client callbacks? Are they local ones or the server provides them? I've noticed that they may have difference between DateTime.UtcNow up to ~20 seconds, but they are still seem not the ones from Bittrex.
The reason why I'm asking is because it's getting hard to correlate the stream data with the candle data from GetMarketCandles, because the candle timestamps may differ from the local time for ~2 minutes.

**Comment by daerhiel** [comment]
It seems that API candles are actually delayed for 1-2 minutes. Stream client gives somewhat the same data but ahead in time, so they either have 2 different servers for candle reports and streaming data that have 1-2 minutes timegap, or... either of two.

**Comment by JKorf** [comment]
Hi, I don't know how Bittrex handles their data, but could be that they have to aggregate the data for the candles before being able to provide them, which could take some time maybe? I don't know. Anyway not much I can do about this, so I'll close this issue.

**Comment by daerhiel** [comment]
Well, formally the question was whether the timestamps come from server or you set the local ones in socket client?

**Comment by JKorf** [comment]
Oh I'm sorry. No data is set on the client side, it's all returned from Bittrex
