### ISSUE TITLE
Exception Object reference not set to an instance of an object in GetLatestCandleAsync

### ISSUE THREAD

**Issue by mariocaptain** [JKorf/Bittrex.Net#65]
Hi all,

I am using the following loop, which is called every 15 minute to get the latest 1/2 hour candles of all available market and buffer them into each respective Azure table. Candles will be inserted into their respective table if such candles have not been inserted earlier.

The weird thing is that in each loop call, there are a number of null exceptions with certain markets (around 10 to 20 each time, these markets change from loop to loop, not the same bunch of markets).

Please see the comment in code for where the Exception occurs.

It's weird since I have check if the call to Bittrex is successful, and if the array has at least 1 element, but r.Result[0] is still null, hence the exception.
```

            foreach (MarketEntity mrkEntity in entities) // entities: all the available markets
            {
                try
                {
                    //Locate the market table
                    table = tableClient.GetTableReference(regulateMarketName(mrkEntity.RowKey));
                    //If it is a newly listed currency, create the table
                    table.CreateIfNotExists();
                    bool isSuccess = false;
                    int numTry = 0;
                    while (!isSuccess)
                    {
                        var r = await client.GetLatestCandleAsync(mrkEntity.RowKey, Bittrex.Net.Objects.TickInterval.HalfHour);
                        if (r.Success && r.Result.Length > 0)
                        {
                            isSuccess = true;
                            //Insert latest candle into the table
                            string ticks = string.Empty;
                            try
                            {
                                ticks = r.Result[0].Timestamp.Ticks.ToString(); // THIS IS WHERE THE EXCEPTION OCCURS
                            }
                            catch (Exception ex)
                            {
                                Trace.TraceInformation("Exception details: " + ex.ToString());
                                break;
                            }
                            CandleEntity candleEntity = new CandleEntity(ticks, mrkEntity.RowKey);
                            candleEntity.Close = (double)r.Result[0].Close;
                            candleEntity.Open = (double)r.Result[0].Open;
                            candleEntity.High = (double)r.Result[0].High;
                            candleEntity.Low = (double)r.Result[0].Low;
                            candleEntity.Volume = (double)r.Result[0].Volume;
                            candleEntity.timeStamp = r.Result[0].Timestamp;

                            //Check if candle already exists
                            TableOperation retrieveOperation = TableOperation.Retrieve<CandleEntity>(candleEntity.PartitionKey, candleEntity.RowKey);
                            TableResult retrievedResult = table.Execute(retrieveOperation);

                            //Create the TableOperation object that inserts the market entity.
                            TableOperation insertOp = TableOperation.Insert(candleEntity);
                            if (retrievedResult.Result == null)
                            {
                                //Trace.TraceInformation("New candle doesn't exists yet. Inserting...");
                                try
                                {
                                    table.Execute(insertOp);
                                }
                                catch (Exception ex)
                                {
                                    Trace.TraceInformation("Exception inserting lastest candle: " + ex.ToString());
                                    break;
                                }
                            }
                            else
                            {
                                //Trace.TraceInformation("Candle already exists. No insertion is needed.");
                            }
                        }
                        else
                        {
                            numTry += 1;
                            if (numTry < 2)
                            {
                                Trace.TraceInformation("Cannot get lastest candles for market: " + mrkEntity.RowKey + ". Re-trying in 2 seconds");
                                await Task.Delay(2000);
                            }
                            else isSuccess = true;
                        }
                    }
                }
                catch (Exception ex)
                {
                    Trace.TraceInformation("Exception inserting market update for " + mrkEntity.RowKey + " in updateMarkets(): " + ex.ToString());
                    continue;
                }
                await Task.Delay(200);
            } // foreach
```
Could this be a bug or something? I remember not having this exception with 1.3.7 (now I am at 1.3.9) but reinstalling 1.3.7 doesn't help either.

Any advice would be greatly appreciated.

Thanks in advance.
Dave

**Comment by daerhiel** [comment]
Hi, I know that occasionally Bittrex returns null as an array item, and I think it's because the Bittrex either limits the number of calls, or somehow mistreats the buffer. Bittrex may return null item subsequently on several calls in a row. I just do up to 10 retries depending how badly I need the data to be returned.

I would recommend to switch to WebSocket client if you want the stream data, it would be more efficient from any standpoint.

**Comment by mariocaptain** [comment]
Thanks Daerhiel,

I appreciate your info and will implement retries.
As for WebSocket, I am actually almost done with REST API so no way back to WebSocket. Besides, I heard that WebSocket is neither designed to be open nor is it very complete so as of now I think I will stick to REST.

Cheers,
Dave

**Comment by daerhiel** [comment]
Hi Dave,

Actually the web socket client is the best, I vote for that. It's lightning fast and gives more info than REST. If you want, I can share snippets for building candles.

Regards.

**Comment by JKorf** [comment]
Hi Dave,

I haven't used the candles rest endpoints extensively so I'm not sure as to what is going wrong, but if there is an null object in the array then that's is what Bittrex has returned, not much I can do about that. I have to agree with @daerhiel , the websocket is better for two reasons.
1. The Candles REST endpoint has a 1-2 minute delay where the websocket are the actual latest values
2. The REST endpoint gets limited on Bittrex side to the point where subsequent calls can take up to 20 seconds before returning. If you're doing a GetCandles call for every market it takes a pretty long time.

It's up to you though.

**Comment by mariocaptain** [comment]
Thanks you two,

I will then definitely look into changing to websocket to see if it would take too much time.
@daerhiel : if you could share the snippet to build candles, it would be highly appreciated.

Thanks again.
Dave

**Comment by mariocaptain** [comment]
Websocket is terrific, its definitely a GO. Wish I went for it from the beginning.

**Comment by JKorf** [comment]
Later on regretting decisions you made earlier is part of programming ;)

**Comment by mariocaptain** [comment]
So true ;) still awaiting @daerhiel 's kind snippet to close the "issue" :)

**Comment by daerhiel** [comment]
How do you want to submit the code? I've made a small project for you.

**Comment by daerhiel** [comment]
I've created a repo with sample :)
https://github.com/daerhiel/Bittrex.Net.Sample

**Comment by mariocaptain** [comment]
Terrific! Thanks Daerhiel!
Dave

**Comment by mariocaptain** [comment]
Terrific! Thanks Daerhiel!
But I can't seem to load the solution file with Visual Studio 2015. The project file doesn't load either. What could be the problem? 
Dave
