### ISSUE TITLE
Use BittrexExchangeState as BittrexStreamExchangeState?

### ISSUE THREAD

**Issue by daerhiel** [JKorf/Bittrex.Net#66]
Hi there,
These 2 classes have the same structure and they basically deliver the same information, if you consider the initial exchange state as stream delta from 'zero'. Why having 2 different objects then? I would suggest using the same object for both getting initial state and streamed delta, this will make writing data providers easier..

**Comment by JKorf** [comment]
You're right, will be fixed in next version

**Comment by JKorf** [comment]
Just pushed new version

**Comment by daerhiel** [comment]
Strange, I see the changes in source code on Git, but the assembly still has old types

`#region Assembly Bittrex.Net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// C:\Users\xxx\.nuget\packages\bittrex.net\1.3.11\lib\netstandard2.0\Bittrex.Net.dll
#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Bittrex.Net.Interfaces;
using Bittrex.Net.Objects;

namespace Bittrex.Net
{
    public class BittrexSocketClient : BittrexAbstractClient
    {
        public const string UserAgent = "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 OPR/48.0.2685.52";
        public IConnectionFactory ConnectionFactory;
        public ICloudFlareAuthenticator CloudFlareAuthenticator;

        public BittrexSocketClient();

        public int CloudFlareRetries { get; set; }

        public static event Action ConnectionLost;
        public static event Action ConnectionRestored;

        public override void Dispose();
        public BittrexApiResult<BittrexExchangeState> QueryExchangeState(string marketName);
        public Task<BittrexApiResult<**BittrexExchangeState**>> QueryExchangeStateAsync(string marketName);
        public void SetProxy(string hostName, int port);
        public BittrexApiResult<int> SubscribeToAllMarketDeltaStream(Action<List<BittrexMarketSummary>> onUpdate);
        public Task<BittrexApiResult<int>> SubscribeToAllMarketDeltaStreamAsync(Action<List<BittrexMarketSummary>> onUpdate);
        public BittrexApiResult<int> SubscribeToExchangeDeltas(string marketName, Action<BittrexStreamExchangeState> onUpdate);
        public Task<BittrexApiResult<int>> SubscribeToExchangeDeltasAsync(string marketName, Action<**BittrexStreamExchangeState**> onUpdate);
        public BittrexApiResult<int> SubscribeToMarketDeltaStream(string marketName, Action<BittrexMarketSummary> onUpdate);
        public Task<BittrexApiResult<int>> SubscribeToMarketDeltaStreamAsync(string marketName, Action<BittrexMarketSummary> onUpdate);
        public void UnsubscribeAllStreams();
        public void UnsubscribeFromStream(int streamId);
    }
}`

**Comment by JKorf** [comment]
Newest version is 1.3.12, I've pushed the package to Nuget but it doesn't show up yet, so there seems to be some delay. When I tried to push it again tells me it already exists, so I guess we'll just wait for a bit till it shows up.

**Comment by daerhiel** [comment]
Oh, I see, thank you..

**Comment by JKorf** [comment]
I've had to do some adjusting because apparently the Fills object is different when receiving an update event rather than the QueryExchangeState response.

To fix this I've made the BittrexExchangeState abstract and created 2 implementations with different Fills objects.

**Comment by daerhiel** [comment]
It works well, thank you.
