### ISSUE TITLE
Trades from WebSocket don't contain Price and Id

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bittrex.Net#68]
Hi, trades that are received by GetMarketHistory contain all the information, but trades from ExchangeDeltas WebSocket Event don't contain Price and Id.
https://www.screencast.com/t/8RyelAlM7R

**Comment by JKorf** [comment]
Hm, Bittrex doesn't seem to put all the information in the Fill object returned from the websocket event. The `Price` field is actually called `Rate`, I'll push a fix for that, but the `Id` and the `Total` field aren't returned in the websocket event. Even though they are returned in the `GetMarketHistory`, and also in the `QueryExchangeState`. I'll update the models to reflect that the event doesn't have an `Id` and `Total` property and the `Price` field is called `Rate` there.

**Comment by JKorf** [comment]
Is fixed in the latest version
