### ISSUE TITLE
BittrexHubConnection.cs errors

### ISSUE THREAD

**Issue by buckyslc** [JKorf/Bittrex.Net#69]
Greetings! I am attempting to use bittrex.net with Unity version 2017.3.1 but getting errors:

"The type or namespace 'AspNet' does not exist in namespace 'Microsoft' "  (I am getting this error in line 5 and 6 of BittrexHubConnection.cs )
and
"The type or namespace '<HubConnection/ConnectionState/etc....>' could not be found"  (also in BittrexHubConnection.cs )

So I have modified to add all the Workloads using Visual Studio Installer that seem relevant to correct missing assembly reference, such as '.NET desktop environment,' 'ASP.NET and web development,' '.NET Core cross-platform', but I have not had success.
I am using Visual Studio Community 2017 version 15.5.7 with
Microsoft .NET Framework 4.7.02556
ASP.NET Core Razor Language Services - 1.0
ASP.NET and Web Tools 2012 4.0.20601.0
ASP.NET and Web Tools 2017 5.2.51007.0

Any suggestions what I am missing? Thanks for any reply!

**Comment by JKorf** [comment]
Hi, I have no experience using Unity, and no version available to test it on, so that's not really helping. What type/namespace is it complaining about?

**Comment by buckyslc** [comment]
Thx for the attention! I think the fact that I am using Unity doesn't matter and we can ignore that, because I am getting the errors directly in the script using Visual Studio, not in Unity.

The 2 main nameplaces it is complaining about are "Microsoft" and "AspNet," with the error "The type or namespace 'AspNet' does not exist in namespace 'Microsoft', in the script "BittrexHubConnection.cs", as seen in these 2 screenshots:
![screenshot 19](https://user-images.githubusercontent.com/16599167/36697380-171edbe0-1b04-11e8-8b1d-d2ebd48ad4ef.png)
![screenshot 20](https://user-images.githubusercontent.com/16599167/36697385-1aea34ea-1b04-11e8-90a9-73cc477eecb4.png)

Visual Studio says that the Microsoft and AspNet namespace "Using directive is unnecessary," but if I comment them out on lines 5 and 6, then I get "The type or namespace name 'HubConnection/ConnectionState/etc...' could not be found," as seen in these 2 screenshots :

![screenshot 21](https://user-images.githubusercontent.com/16599167/36697810-6c66780a-1b05-11e8-9f41-2b100a7f11ca.png)
![screenshot 18](https://user-images.githubusercontent.com/16599167/36697819-6f5ee376-1b05-11e8-97a6-94127cc166d5.png)

I think I have all the current .NET and ASP.NET workloads/components installed:
Visual Studio Community 2017 version 15.5.7 
Microsoft .NET Framework 4.7.02556
ASP.NET Core Razor Language Services - 1.0
ASP.NET and Web Tools 2012 4.0.20601.0
ASP.NET and Web Tools 2017 5.2.51007.0

Are other workloads/components needed for the Asp.Net nameplace to work?

**Comment by JKorf** [comment]
Not sure why it cannot find those references. Can you verify the `Microsoft.AspNet.SignalR.Client` package is referenced? Maybe (re)add it?

**Comment by buckyslc** [comment]
Thanks for your response - I do have the Microsoft.AspNet.SignalR.Client package referenced and I re-added it and that wasn't the issue, BUT:

I have researched some more on my end, and I believe the issue I'm experiencing is that bittrex.net does not currently (as of v2.0.1) support any of the 3 frameworks that Unity supports. I think there is an easy fix, but which I can't do on my end, so wanted to make a request to you to add Unity support for the next updated version that you make. This can be done simply by modifying prior to compiling, and adding in a check for the "Visual Studio Tools for Unity" under "Individual components/Games and Graphics." Here's a screenshot of what that looks like in Visual Studio: 

![screenshot 24](https://user-images.githubusercontent.com/16599167/36925479-5a0d28c4-1e30-11e8-901c-278238f19c17.png)

That should solve my issue. If that makes sense, and is doable on your end when you next update, we'd really appreciate it! That would allow us to move forward with doing some real time data visualization that we are eager to do. Thanks for your help and lemme know if any questions.

**Comment by JKorf** [comment]
Is this something I have to add to my Visual Studio installation? And do I also need to install Unity for that? What would that add when compiling the library? Love to help, just trying to understand.

**Comment by buckyslc** [comment]
> > Is this something I have to add to my Visual Studio installation? 
Yes, all you have to do is run Visual Studio Installer, click "modify," click "Individual components," scroll down to the "Games and Graphics" tab, and check the box next to "Visual Studio Tools for Unity."

> > Is this something I have to add to my Visual Studio installation? 
You do not have to install Unity. 

> >What would that add when compiling the library?
This will add the ability of bittrex to use the same framework that Unity does.

That should do it!

**Comment by JKorf** [comment]
I did as you asked, and version 2.0.4 is compiled with the Unity tools installed. Not sure if it changed anything, but you can try.

**Comment by JKorf** [comment]
@buckyslc did this help, or do we need to try something else?
