### ISSUE TITLE
Call failed: Could not connect to Bittrex server

### ISSUE THREAD

**Issue by wklm** [JKorf/Bittrex.Net#7]
Http error 400 (bad request) is returned from signalr api when I try to connect

```
10:47:09:206 | Error | Socket error: StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
{
  Date: Mon, 20 Nov 2017 09:47:09 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Cache-Control: no-cache
  Pragma: no-cache
  X-Content-Type-Options: nosniff
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=15768000
  X-XSS-Protection: 1; mode=block
  X-Download-Options: noopen
  Server: cloudflare-nginx
  CF-RAY: 3c0a7c717d844304-MXP
  Content-Type: text/html
  Expires: -1
}
10:47:09:214 | Warning | Call failed: Could not connect to Bittrex server
```

My code:
```
let ws = new BittrexSocketClient() 
ws.SubscribeToMarketDeltaStream(pair.symbol, fun x -> printfn "%A" x)
```

Could it be related to cloudflare? 
Downgrading to `1.2.0` which worked previously doesn't solve the problem

**Comment by JKorf** [comment]
Hi, thanks for reporting the issue. It seems that Bittrex changed some things on the server side regarding the websockets. I have to check what they changed and how to fix it.

**Comment by wklm** [comment]
Thanks a lot :) Btw. When something goes wrong you're calling `ThrowErrorMessage` instead of throwing an actual exception. What's the reason for that? How could I catch it?

**Comment by JKorf** [comment]
The subscribe method returns a success indicator (in C#):
`
var ws = new BittrexSocketClient();
var result = ws.SubscribeToMarketDeltaStream(pair.symbol, data => Console.WriteLine(data));
if(result.Success)
    Console.WriteLine("Subscribed");
else
    Console.WriteLine("Oh no, something went wrong: " + result.Error.ErrorMessage);
`

**Comment by wklm** [comment]
thank you!

**Comment by JKorf** [comment]
No problem. I've pushed a fix for the connection issue, this should mean you should be able to connect again. It is however a temporary fix and I don't know how long it will hold. Bittrex is running an older version of the socket implementation on an alternative URL(https://socket-stage.bittrex.com). This endpoint works as the old one did before the changes, but I expect the alternative endpoint to be changed or go offline somewhere in the future. 

I hope this helps you while I try to figure out how to fix the problem. I created a new Issue for this:  #8.
