### ISSUE TITLE
How to set API credentials properly

### ISSUE THREAD

**Issue by pwnzya** [JKorf/Bittrex.Net#71]
Hello.

I updated Bittrex.Net to version 2.0.0, and now I am not sure how to set the api credentials properly.
I am receiving error from Bittrex when I try to get, for example, my account balance information like this:

COMMAND:
```
var result = await client.GetBalancesAsync();
```
RESULT:
```
result.Success = false
result.Error.Message = "Server error: Server returned error: Bad Request"
result.Data = null
```

With the previous version (ver. 1.4.1), I first created a client, then did something like
```
client.SetKey(myKey)
client.SetSecret(mySecret)
```
and all worked fine.

However, after updating Bittrex.Net to the latest version (ver. 2.0.0), I used
```
client.SetApiCredentials(myKey, mySecret)
```
to set the api credentials, but GetBalancesAsync() returns the error I mentioned above.

Please, tell me what I am missing here.

Last but not least, thanks for your hard work on the great library! :)

**Comment by JKorf** [comment]
Hi, what you're doing is okay. You could also use the BittrexClientOptions parameter in BittrexClient to provide them: 
````C#
var client = new BittrexClient(new BittrexClientOptions() { ApiCredentials = new ApiCredentials("KEY", "SECRET") })
````
Or set them as default for every client you create:
````C#
BittrexClient.SetDefaultOptions(new BittrexClientOptions() { ApiCredentials = new ApiCredentials("KEY", "SECRET"));
````

There was a little bug in the URL building, which is where the error you got came from. I pushed a new version to fix this.

**Comment by pwnzya** [comment]
Works fine now. Thank you.
