### ISSUE TITLE
place order invalid permission

### ISSUE THREAD

**Issue by ragekillen** [JKorf/Bittrex.Net#72]
Hello I am attempting to place a order like so

    if (Convert.ToDecimal(currprice) < Convert.ToDecimal(sellprice))
    {
        quantity = Convert.ToDecimal(balance) / Convert.ToDecimal(currprice);
        var placeOrder = bitclient.PlaceOrder(OrderSide.Buy, comboBox1.Text + "-" + comboBox2.Text, quantity, price);
         if (placeOrder.Success)
         {
             purprice = currprice;
             label7.Text = purprice;
             label5.Text = "Selling";
             mode = "SELL";
           }
           else
           {
               MessageBox.Show($"{placeOrder.Error.ErrorMessage}");
           }
    }

the issue i have is right after If(placeorder.success) it jumps to the else and the message states INVALID_PERMISSION

I may be just handling the statement wrong but as far as i can tell its perfect.

 yes all my permissions are checked on bittrex, and my key/secret are right because it retrieves my balance

This is for V1.4.1 and i have not been able to update due to your dependency list not including 4.X

as for the dependency error on updating to 2.0.1 i get this

    Could not install package 'Bittrex.Net 2.0.1'. You are trying to install this package into a 
    project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly 
    references or content files that are compatible with that framework. For more information, contact the 
    package author.

**Comment by JKorf** [comment]
Hi, I'm not sure why it would return Invalid permission. That's what a Bittrex response, haven't seen it before as far as in can recall. 

Regarding the dependency error, could you try updating your Nuget client? This fixed it for someone else.

**Comment by ragekillen** [comment]
I believe the issue resolved its self must have been a bittrex server issue as of now i get dust_trade_disallowed_min_value_50k_sat which if i recall is caused by trade being bellow 0.0005 as i only put 2$ for balance retrieval testing

**Comment by JKorf** [comment]
Okay bit weird but glad it's resolved. The error you got now indeed means that the order is too small.

What version of the nuget client are you running currently? And what version of visual studio? I'd like to figure out what the problem is for future reference :)

**Comment by ragekillen** [comment]
my version is 3.4.4.1321 on visual studio 2015 and it installed v 1.4.1 without issues from nuget

**Comment by JKorf** [comment]
Can you try to install v3.6 and see if that works? Its a small download on https://www.nuget.org/downloads, on the right. 

The reason you are able to install v1.4.1 is that it has explicit support for .net 4.5 and 4.6 as well as .netstandard2.0. However supporting .netstandard2.0 automatically makes the package available for .net framework 4.5 and 4.6, so I removed these explicit references, but that means that visual studio and the nuget client have to understand the .netstandard2.0 package, which may require some updating. 

Most solid solution is to use VS 2017, but again, it should also work in 2015 with some updates.
