### ISSUE TITLE
Version 2.0.1 not working

### ISSUE THREAD

**Issue by rokeefe1** [JKorf/Bittrex.Net#74]
This code is not working:

`var balances = _client.GetBalances().Data;`

The debugger never moves on to the next line of code.

**Comment by JKorf** [comment]
Hi, I see the problem. If you make sure it's not running on the UI thread it should work. You can do this by surrounding the call in a Task.Run(); call, e.g.:
````C#
Task.Run(() => {
    var balances = _client.GetBalances().Data;
});
````
This will be fixed in next version, after which you wouldn't need the Task.Run anymore.

**Comment by JKorf** [comment]
Should be fixed in last version
