### ISSUE TITLE
Fix websocket connection after breaking Bittrex changes

### ISSUE THREAD

**Issue by JKorf** [JKorf/Bittrex.Net#8]
After changes to the websocket implementation of Bittrex we can't connect anymore to the official endpoint. Figure out how so and switch connection back to new endpoint.

**Comment by JKorf** [comment]
Seems like they don't support serverSentEvents protocol anymore. This was the automatic fallback for when the websockets protocol is not available.
`https://socket-stage.bittrex.com/signalr/connect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[{%22Name%22:%22coreHub%22}]&connectionToken=2LpLVf6wVHJZZny3Ui73gc7ogwntFd7OZPF%2ByA1%2BXH9EKrXKa7IgCtkNuLlDoPBe0E%2FedBNwWlkjKPIaw%2BYTcnOcE5duzllR91oW%2B6rr1SxYeJYF`
 works, but 
`https://socket.bittrex.com/signalr/connect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[{%22Name%22:%22coreHub%22}]&connectionToken=2LpLVf6wVHJZZny3Ui73gc7ogwntFd7OZPF%2ByA1%2BXH9EKrXKa7IgCtkNuLlDoPBe0E%2FedBNwWlkjKPIaw%2BYTcnOcE5duzllR91oW%2B6rr1SxYeJYF` doesn't

**Comment by wklm** [comment]
Since we're discussing  the websockets client. Would it be fine to refactor the `SubscribeToMarketDeltaStream` so it returns a `Task<BittrexApiResult>` ? I was also thinking that it may be a perfect use case for Akka.Net stream

Now it returns synchronous `BittrexApiResult` which isn't very handy 
```return new BittrexApiResult<int>() {Result = registration.StreamId, Success = true};```

**Comment by JKorf** [comment]
I agree refactoring the subscribe method to a Task would be beneficial. If you create a new issue for this I'll get to it. My first priority now however is getting the socket connection back up. 

This is the first time I hear about Akka.Net, what is it and how would it help?

**Comment by wklm** [comment]
It's a framework for an Actor model for .NET 
Turning it to reactive stream may help with scalability and performance
https://stackoverflow.com/questions/46676892/where-to-put-websocket-clients-for-a-proxy-in-akka-net-inside-or-outside-actors

**Comment by JKorf** [comment]
I have to say I don't feel like implementing Akka.Net would benifit the Api wrapper much. I won't implement it at this moment.

On topic; 
Connection works on Windows 10 PC because websocket protocol is supported. However the implementation has changed and the socket no longer sends the update messages by default.

**Comment by mmartain** [comment]
I jus happens that i discovered this nuget package today and wanted to use it for streaming :) I guess bad timing... Looking forward for the fixed version!

**Comment by wklm** [comment]
I see, shall I create an issue though regarding the change of returned type to `Task`?

**Comment by JKorf** [comment]
Yes please do.

On topic (and @mmartain );
For now the socket connection will work with the socket-stage.bittrex.com endpoint running the old implementation. When inevitably this endpoint gets updated or taken down, code is ready in a separate branch to immediately update to the new implementation. Sadly, the new implementation required the websockets protocol to be available on the operating system, meaning that it is no longer possible to connect using Windows 7 (Only Windows 8 and up). For this reason I'll stick to the socket-stage endpoint as long as it works.

**Comment by mmartain** [comment]
Thanks! will this update be pushed to nuget?

**Comment by JKorf** [comment]
The latest version (1.2.2) should work already.

**Comment by JKorf** [comment]
I've been able to create a workaround for the issue that Windows 7 doesn't support websockets. The latest version uses the new Bittrex implementation and works on all platforms :). (Functionality hasn't changed, just the internal implementation which means we're no longer reliant on a temporary alternative endpoint)

**Comment by wklm** [comment]
> Seems like they don't support serverSentEvents protocol anymore. This was the automatic fallback for when the websockets protocol is not available.
> https://socket-stage.bittrex.com/signalr/connect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[{%22Name%22:%22coreHub%22}]&connectionToken=2LpLVf6wVHJZZny3Ui73gc7ogwntFd7OZPF%2ByA1%2BXH9EKrXKa7IgCtkNuLlDoPBe0E%2FedBNwWlkjKPIaw%2BYTcnOcE5duzllR91oW%2B6rr1SxYeJYF
> works, but
> https://socket.bittrex.com/signalr/connect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[{%22Name%22:%22coreHub%22}]&connectionToken=2LpLVf6wVHJZZny3Ui73gc7ogwntFd7OZPF%2ByA1%2BXH9EKrXKa7IgCtkNuLlDoPBe0E%2FedBNwWlkjKPIaw%2BYTcnOcE5duzllR91oW%2B6rr1SxYeJYF doesn't

Now both of the urls are returning `400` :(

**Comment by JKorf** [comment]
Same for me, seems they updated the socket-stage to new version as well. Newest version of Bittrex.Net has already implemented the new version so if you have the latest version you should be good.

**Comment by wklm** [comment]
Unfortunately I'm not. It tries the cloudflare bypass and fails

**Comment by JKorf** [comment]
That's weird, it works on my end. Which version do you have?

**Comment by wklm** [comment]
It looks like my ip is blacklisted for some reason. It's strange because I can log in to the web panel from the very same computer

**Comment by JKorf** [comment]
That´s odd.. Maybe you were requesting too frequently?

**Comment by wklm** [comment]
@JKorf I turned out that it was some weird issue with my vpn configuration. Everything works smoothly now :)

**Comment by marcelmolenaar** [comment]
Does someone know if we can still use the BitTrex websocket? i am trying for hours now but the only thing i get is "bad request". I think it has something to do with bypassing the CloudFlare. Anyways, does someone have a good example of a PHP client to access the BitTrex websocket?

**Comment by JKorf** [comment]
What is the problem? It works fine for me

**Comment by marcelmolenaar** [comment]
@JKorf , i am just trying to invent a plain PHP websocket client by using PHP's socket functions like stream_socket_client() to access the BitTrex websocket to get ticker data to store in my local database. I am currently using the BitTrex REST api but because of polling issues i sometimes mis some data so that's why i am investigating the BitTrex websocket possibility.

**Comment by JKorf** [comment]
I see. An old issue on a C# implementation is probably not the place to ask about a PHP implementation though
