### ISSUE TITLE
"Method not found" after SubscribeToAllMarketDeltaStream 

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bittrex.Net#80]
After call BittrexSocketClient.SubscribeToAllMarketDeltaStream exception is raised...

 InnerException | {"Method not found: 'Void Microsoft.AspNet.SignalR.Client.Hubs.Subscription.add_Received(System.Action`1<System.Collections.Generic.IList`1<Newtonsoft.Json.Linq.JToken>>)'."} | System.Exception {System.MissingMethodException}

It works fine with Bittrex.Net 2.0.2.

**Comment by JKorf** [comment]
What version are you using?

**Comment by NektoDron** [comment]
2.0.8

**Comment by JKorf** [comment]
Hm I can't reproduce the issue. What are the versions of CrytpoExchange.Net, CloudFlareUtilities and Microsoft.AspNet.SignalR.Client? Seems like there is a mismatch somewhere.

**Comment by NektoDron** [comment]
Sorry, It was conflict with old Newtonsoft.Json.dll from other libs.
It can be closed.
