### ISSUE TITLE
New Bittrex Beta Released

### ISSUE THREAD

**Issue by pwnzya** [JKorf/Bittrex.Net#82]
Hello.

I just noticed that Bittrex has released a new beta version of their website (https://beta.bittrex.com) and API documentation (https://github.com/Bittrex/beta). They tweeted about it on March 28, 2018.

It may be the reason why some of us have been experiencing issues with keeping a stable connection to Bittrex.

@JKorf, please, check them out, and tell us if you need to update your library, and whether you will update it or not.

Thanks.

**Comment by JKorf** [comment]
I've pushed an update (v2.1.0) which uses the new beta implementation. Please let me know if something isn't working.

**Comment by pwnzya** [comment]
Thanks for the quick fix @JKorf !

I am testing
- SubscribeToMarketSummariesUpdateAsync
- QueryExchangeStateAsync
- SubscribeToExchangeStateUpdatesAsync
- SubscribeToBalanceUpdatesAsync

and they are all working smoothly so far. 👍

By the way, is it OK to update 
- CloudFlareUtility to v1.2.0
- NewtonSoft.Json to v11.0.2
- Microsoft.AspNet.SignalR.Client to v2.2.3

?

Thanks.

**Comment by JKorf** [comment]
Yes that should be okay. I'll try to remember to update the references in the next release ;)

**Comment by pwnzya** [comment]
I just observed the following subscriptions all reconnected successfully almost at the same time:
- SubscribeToMarketSummariesUpdateAsync
- SubscribeToExchangeStateUpdatesAsync
- SubscribeToBalanceUpdatesAsync

It confirmed v2.1.0 fixed the issue for my purpose. Thank you @JKorf 👍
