### ISSUE TITLE
Bittrex Socket Exchange Deltas Not Working

### ISSUE THREAD

**Issue by mclean25** [JKorf/Bittrex.Net#83]
Not sure if Bittrex changed something in their backend but subscribing to `SubscribeToExchangeDeltas()` doesn't seem to work:

```
2018/04/04 06:53:50:227 | Info | Subscribing to exchange deltas for BTC-XLM
2018/04/04 06:53:50:242 | Info | Starting connection to bittrex server
2018/04/04 06:53:50:265 | Warning | Getting CloudFlare cookies
2018/04/04 06:54:47:302 | Error | CloudFlareAuthenticator didn't give us the cookies, trying to start without
2018/04/04 06:54:47:437 | Info | Socket closed
2018/04/04 06:54:47:441 | Warning | Couldn't connect. Microsoft.AspNet.SignalR.Client.HttpClientException
```

**Comment by TobyBee** [comment]
I found this link for the Websocket Sample for the new Website, maybe it will help to fix this Problem :).
https://github.com/Bittrex/beta/blob/master/samples/WebsocketSample.cs

Best regards

**Comment by JKorf** [comment]
Bittrex has been working on their websocket implementation. 28th of march they released a new Beta of the websocket, which is what I'll have to use from now on, but I need to implement some changes (#82). The websocket that was used until now was never officially supported by Bittrex. That websocket still exists, but is behind CloudFlare protection. CloudFlare changed some things the last days which prevents us currently from accessing the websocket. I think this issue on the library I use to bypass the CloudFlare protection is related:
https://github.com/elcattivo/CloudFlareUtilities/issues/30

I'll try to quickly update to the new Beta implementation to get it to working again.

**Comment by JKorf** [comment]
I've pushed an update (v2.1.0) which uses the new Bittrex beta socket implementation. Please let me know if something isn't working.
