### ISSUE TITLE
INSUFFICIENT_FUNDS problem when PlaceConditionalOrderAsync

### ISSUE THREAD

**Issue by ndphuong** [JKorf/Bittrex.Net#86]
Hi,
I have check balance and see available is enough
But problem still happen when I try create new stoploss order with PlaceConditionalOrderAsync
`var result = await client.PlaceConditionalOrderAsync(OrderSide.Sell, TimeInEffect.GoodTillCancelled, market, quantity, dActualRate, ConditionType.LessThan, rate);`

**Comment by JKorf** [comment]
Make sure you have enough to pay the transaction fees. Every trade has a 0.25% fee, so you can only trade for 99.75% of your total balance.

**Comment by JKorf** [comment]
Could that have been the problem you we're having?

**Comment by JKorf** [comment]
I'll assume this is fixed, if not please re-open the issue
