### ISSUE TITLE
GetOrderHistory was locked for hours

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bittrex.Net#87]
GetOrderHistory was blocked for several hours. At that time, there were no more threads from Bittrex library.
![2018-04-12_1055](https://user-images.githubusercontent.com/26095298/38663713-4569a264-3e40-11e8-8cb0-df89d77d1d6a.png)

Also question I have about new method SubscribeToOrderUpdates from SocketApi. It doesn't work. Updates come never.

**Comment by JKorf** [comment]
Hi, do you have any logging of when it blocked? Also, it was working before?

Regarding the order updates, you did provide your API credentials to the socket client? And do you have logging from when you're subscribing to order updates?

**Comment by NektoDron** [comment]
Sorry, I have no logs from library. The code updates balances and order history every 1000ms by timer.

And I forgot to use API credentials for socket API. It works. Thanks.

**Comment by NektoDron** [comment]
Hi, I got connection restoring with version. The code doesn't use any more.
But after socket reconnecting all active of subscriptions was dropped was not restored.
Should I restore it on "ConnectionRestored" event or it's a bug?



21:23:54.38[2]FATAL:UnobservedTaskExceptio: 
System.AggregateException: При ожидании задачи или доступе к ее свойству исключения не были замечены исключения задачи. В результате незамеченные исключения были созданы повторно потоком завершения. ---> System.InvalidOperationException: Connection was disconnected before invocation result was received.
   --- Конец трассировки внутреннего стека исключений ---
---> (Внутреннее исключение #0) System.InvalidOperationException: Connection was disconnected before invocation result was received.<---

21:22:14.72[1727]DEBUG:[Bittrex] API: 2018/04/16 09:22:14:723 | Info | Socket closed
21:22:14.72[1727]WARN :[Bittrex] WebSocket connection is lost.
21:22:14.72[1727]DEBUG:[Bittrex] API: 2018/04/16 09:22:14:723 | Error | Socket error: The client has been inactive since 16.04.2018 18:21:21 and it has exceeded the inactivity timeout of 00:00:50. Stopping the connection.
21:22:29.48[1673]DEBUG:[Bittrex] API: 2018/04/16 09:22:29:485 | Info | Socket connection established
21:22:29.48[1635]DEBUG:[Bittrex] API: 2018/04/16 09:22:29:488 | Info | (re)subscribing 5 subscriptions

21:22:59.49[1727]DEBUG:[Bittrex] API: 2018/04/16 09:22:59:494 | Info | Socket closed
21:22:59.76[1659]DEBUG:[Bittrex] API: 2018/04/16 09:22:59:761 | Warning | Failed to invoke proxy: Connection was disconnected before invocation result was received.
21:22:59.76[1635]DEBUG:[Bittrex] API: 2018/04/16 09:22:59:767 | Warning | Failed to resubscribe exchange delta: 5: Unknown error occured Failed to invoke proxy: Connection was disconnected before invocation result was received.
21:22:59.77[1635]DEBUG:[Bittrex] API: 2018/04/16 09:22:59:779 | Warning | Failed to invoke proxy: Data cannot be sent because the connection is in the disconnected state. Call start before sending any data.
21:22:59.78[1635]DEBUG:[Bittrex] API: 2018/04/16 09:22:59:780 | Warning | Failed to resubscribe exchange delta: 5: Unknown error occured Failed to invoke proxy: Data cannot be sent because the connection is in the disconnected state. Call start before sending any data.
21:22:59.78[1635]DEBUG:[Bittrex] API: 2018/04/16 09:22:59:780 | Warning | Failed to invoke proxy: Data cannot be sent because the connection is in the disconnected state. Call start before sending any data.
21:22:59.78[1635]DEBUG:[Bittrex] API: 2018/04/16 09:22:59:780 | Warning | Failed to resubscribe summary delta: 5: Unknown error occured Failed to invoke proxy: Data cannot be sent because the connection is in the disconnected state. Call start before sending any data.
21:22:59.78[1635]DEBUG:[Bittrex] API: 2018/04/16 09:22:59:780 | Info | Starting connection to bittrex server


21:23:31.04[1580]DEBUG:[Bittrex] API: 2018/04/16 09:23:31:040 | Info | Socket closed
21:23:31.04[1580]DEBUG:[Bittrex] API: 2018/04/16 09:23:31:041 | Warning | Couldn't connect. System.TimeoutException
21:23:31.04[1635]DEBUG:[Bittrex] API: 2018/04/16 09:23:31:041 | Warning | Failed to re-authenticate: 1: Can't connect to the server
21:23:31.04[1635]DEBUG:[Bittrex] API: 2018/04/16 09:23:31:042 | Info | Starting connection to bittrex server

**May be it because exception was**
21:23:54.38[2]FATAL:UnobservedTaskExceptio: 
System.AggregateException: При ожидании задачи или доступе к ее свойству исключения не были замечены исключения задачи. В результате незамеченные исключения были созданы повторно потоком завершения. ---> System.InvalidOperationException: Connection was disconnected before invocation result was received.
   --- Конец трассировки внутреннего стека исключений ---
---> (Внутреннее исключение #0) System.InvalidOperationException: Connection was disconnected before invocation result was received.<---

21:24:10.41[1732]DEBUG:[Bittrex] API: 2018/04/16 09:24:10:413 | Info | Socket closed
21:24:10.41[1732]DEBUG:[Bittrex] API: 2018/04/16 09:24:10:413 | Warning | Couldn't connect. System.TimeoutException
21:24:10.42[1635]DEBUG:[Bittrex] API: 2018/04/16 09:24:10:429 | Warning | Failed to re-authenticate: 1: Can't connect to the server
21:24:10.42[1635]DEBUG:[Bittrex] API: 2018/04/16 09:24:10:429 | Info | Reconnected
21:24:10.42[1635]WARN :[Bittrex] WebSocket connection is restored.

**Comment by JKorf** [comment]
Hi, this looks like a bug. When the connection was restored it tried to restore the subscriptions by sending the command to the Bittrex server, but the connection dropped again while doing that. I'll look into making that more robust.

**Comment by JKorf** [comment]
I've pushed a new version that should fix this, please try that. Let me know if you have any other issues.
