### ISSUE TITLE
Issue in installing from Nuget

### ISSUE THREAD

**Issue by wasimjee** [JKorf/Bittrex.Net#88]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Bittrex.Net 2.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by wasimjee** [comment]
hi, @JKorf i am using 2017

**Comment by JKorf** [comment]
Is it updated to the latest version? Have you also installed .net core sdk? https://www.microsoft.com/net/download/windows

**Comment by wasimjee** [comment]
ok let me try

**Comment by wasimjee** [comment]
Still getting this

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project Bittrex.Net is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Project Bittrex.Net supports: netstandard2.0 (.NETStandard,Version=v2.0)			0

**Comment by JKorf** [comment]
Do you have visual studio version 15.3 or later?

**Comment by wasimjee** [comment]
![image](https://user-images.githubusercontent.com/13384695/38726769-c51e9e18-3f28-11e8-864e-8ae955de77d1.png)

**Comment by JKorf** [comment]
That is version 15.0, you Will need to update to at least 15.3

**Comment by wasimjee** [comment]
Thanks @JKorf , i upgraded and now its working
