### ISSUE TITLE
Client Console Examples Error

### ISSUE THREAD

**Issue by ulaskayalar** [JKorf/Bittrex.Net#92]
1. The SubscribeToMarketDeltaStream is not found.

2. "BittrexClientOptions" does not have a "LogWriter" definition.

I get these errors in the console application, can you help?

**Comment by JKorf** [comment]
Hi, the example is based on an older version. `SubscribeTomarketDeltaStream` is now `SubscribeToMarketSummariesUpdate`, and `LogWriter` is now `LogWriters`.

**Comment by JKorf** [comment]
I've updated the examples, should work for you now aswel.
