### ISSUE TITLE
Point socket client to main when CloudFlare protection is disabled

### ISSUE THREAD

**Issue by pwnzya** [JKorf/Bittrex.Net#93]
Hello.

In case anyone missed it, about three days ago, Bittrex made the announcement as follows:

> The Beta announced on March 27, 2018 has concluded. The Websocket documentation previously located here has been moved to [bittrex.github.io.](https://github.com/Bittrex/bittrex.github.io)
>
> This repo will be archived after all open issues are resolved.

From reading Bittrex/beta#22 and comments in Bittrex Slack, my understanding is that:
- The production socket endpoint (socket.bittrex.com/signalr) is now using the new "beta" API, but is under CloudFlare protection.
- The Beta socket endpoint (beta.bittrex.com/signalr) is not under CloudFlare protection, and remains available until they drop the CloudFlare protection from the production socket endpoint (socket.bittrex.com/signalr).  After that, the Beta socket endpoint will be closed.

Note that, Bittrex.Net (CloudFlareUtilities library) might not be able to bypass CloudFlare probably due to this (elcattivo/CloudFlareUtilities#30) problem.
So, for now, we need to use the Beta socket endpoint.

I will report back here when they announce closure of the Beta socket.

@JKorf If you haven't joined Bittrex Slack yet, you most likely can get an invite in the beta#22 thread as you are a Bittrex API wrapper developer.  I thought you might be interested since, in the beta#22 thread, the Bittrex guy suggested developers to join their Slack for news and updates.

**Comment by JKorf** [comment]
Hi, thanks for notifying me about this, didn't know the beta ended, I asked for an invite for the Slack as well.

For now nothing has to be done, but when Bittrex removes CF on the main we should switch it. I'll keep this issue open to not forget.

**Comment by JKorf** [comment]
Thanks for the update, sadly I didn't get an invite for the slack channel yet. I've moved from the beta endpoint to the socket.bittrex.com endpoint. 

I'll have to look into bypassing CloudFlare again since they state the will enable it whenever it is necessary. Ill create a new issue for that and consider this on closed.

**Comment by pwnzya** [comment]
I asked them to send you an invite just now.
I linked your [github profile page](https://github.com/JKorf) so they can find your email address to send the invite.

**Comment by QuocTan** [comment]
`// Websocket
            var socketClient = new BittrexSocketClient();
            var subscription = socketClient.SubscribeToMarketSummariesUpdate(summaries =>
            {
                Console.WriteLine($"BTC-ETH: {summaries.SingleOrDefault(s => s.MarketName == "BTC-ETH")?.Last}");
            });
`
delay about 5s how i can get faster?
