### ISSUE TITLE
Can't figure out how to print the json response

### ISSUE THREAD

**Issue by hamkline** [JKorf/Bittrex.Net#94]
Really sorry because I know this is a stupid question, but I can't figure it out (just started learning c#)  
Here's what I'm trying to do:
```
var markets = client.GetMarkets();
var price = client.GetTicker("BTC-ETH");
if (markets.Success)
Console.WriteLine($"Market result: {markets.Data}");
else
Console.WriteLine($"Error: {markets.Error.Message}");
if (price.Success)
Console.WriteLine($"Ticker result: {price.Data.Ask}");
else
Console.WriteLine($"Error: {price.Error.Message}");
```
price.data.ask works, it gives me the ask price, but the others won't give me anything other than "Market result: Bittrex.Net.Objects.BittrexMarket[]"

I'd like a response like this to work with: 
```
{
	"success" : true,
	"message" : "",
	"result" : [{
			"MarketCurrency" : "LTC",
			"BaseCurrency" : "BTC",
			"MarketCurrencyLong" : "Litecoin",
			"BaseCurrencyLong" : "Bitcoin",
			"MinTradeSize" : 0.01000000,
			"MarketName" : "BTC-LTC",
			"IsActive" : true,
			"Created" : "2014-02-13T00:00:00"
		}, {
			"MarketCurrency" : "DOGE",
			"BaseCurrency" : "BTC",
			"MarketCurrencyLong" : "Dogecoin",
			"BaseCurrencyLong" : "Bitcoin",
			"MinTradeSize" : 100.00000000,
			"MarketName" : "BTC-DOGE",
			"IsActive" : true,
			"Created" : "2014-02-13T00:00:00"
		}
    ]
}
```

**Comment by JKorf** [comment]
Hi, the [] in Bittrex.Net.Objects.BittrexMarket[] means that it is an array of Bittrex.Net.Objects.BittrexMarket objects; multiple items. To access the first item you can do:
`markets.Data[0]`
To loop through all markets you can use a foreach loop like this:
````C#
foreach(var marketData in markets.Data)
{
    Console.WriteLine(marketData.MarketName);
}
````

**Comment by JKorf** [comment]
That should do it yes. The library automatically parses the json received to usable C# objects, which is generally what you want.

I actually did a Computer Science study where I learned the basics, and work as a software developer now, so basically just learning for experience.
