### ISSUE TITLE
SubscribeToMarketSummariesUpdate not printing sequentially 

### ISSUE THREAD

**Issue by hamkline** [JKorf/Bittrex.Net#95]
My main method is running wild, it keeps going even though I call for another function.  

```
            var socketClient = new BittrexSocketClient();

            Client1 bot = new Client1();
            Console.WriteLine("Main0, before filter method");
            bot.Filter(socketClient);
            //bot.BuyMethod("BTC-ETH");
            Console.WriteLine("Main1");
            Console.WriteLine("Main2");
            Console.WriteLine("Main3");
            Console.ReadLine();          
            socketClient.UnsubscribeAllStreams();            
            Console.WriteLine("DCed from sockets");
            Console.ReadKey();
```

Here's Client1 class:

```
class Client1
{
    public void Filter(BittrexSocketClient skt)
        {            
            Console.WriteLine("Filter Method 1");
            var subscription = skt.SubscribeToMarketSummariesUpdate(summaries =>
            {
                Console.WriteLine("Filter Method 2");
                Console.WriteLine("Filter Method 3");
            });
}
```

Output: 
```
Main0, before filter method
Filter Method 1
Main1
Main2
Main3
Filter Method 2
Filter Method 3
...
loop on Filter 2 and 3
```

SubscribeToMarketSummariesUpdate isn't async or anything, why isn't the output main0 > filter1, filter2, filter3... filter2-3 loop?
I need it to run sequentially, to never go for main method again.
(I learned about async just yesterday, sorry if it's a stupid question)

**Comment by every1no1** [comment]
Console.WriteLine("Filter Method 2"); and Console.WriteLine("Filter Method 3"); get called once you get a summary update from bittrex. if u want to run in sequence then u can do 

class Client1
{
    public void Filter(BittrexSocketClient skt)
        {            
            Console.WriteLine("Filter Method 1");
            Console.WriteLine("Filter Method 2");
            Console.WriteLine("Filter Method 3");
            var subscription = skt.SubscribeToMarketSummariesUpdate(summaries =>
            {
                Console.WriteLine("Filter Method 2");
                Console.WriteLine("Filter Method 3");
            });
}

**Comment by hamkline** [comment]
I mean, I want to only run this method from class Client1 and nothing more at the same time.

Think about it like this: I have `main `and it has a call for `method1(), method2(), and method3().` I want to do `method1 `and only go for `method2 `when `method1 `is done for. 
Like so, `Client1 Filter(BittrexSocketClient skt)` isn't doing that. When it enters the `var subscription = skt.SubscribeToMarketSummariesUpdate(summaries =>` part, the main method continues to do stuff for some reason. In this example it's like `main `would run `method2 `while the subscription part is running.

There's something not respecting the sequence I just don't know if it's something on websockets or c#, cause I'm new to both.

Really sorry if it's confusing, I just can't find what's happening.

**Comment by JKorf** [comment]
You're a bit confused on how the subscribe call works I think. 

The `SubscribeToMarketSummariesUpdate(action)` is basically registering an event handler on the websocket. It says: If a MarketSummary update is received on the websocket, then executed the action I passed in the Subscribe call. The Subscribe call doesn't wait for that event to happen, it just registers the event handler and continues. 

If you want to simply get the market summaries one time and wait for that and not receive updates every x seconds you should probably not use the socket client, but rather the rest client:
````C#
using(var client = new BittrexClient())
{
     marketSummaries = client.GetMarketSummaries();
}
````

**Comment by JKorf** [comment]
I'll assume you got the idea, let me know if you're having any trouble.
