### ISSUE TITLE
ToString()

### ISSUE THREAD

**Issue by sergey-prokhorov** [JKorf/Bittrex.Net#96]
hello! thank You for solution!
I think all objects should have a ToString() method.

**Comment by JKorf** [comment]
Hi,
Although I can see how/where it would be useful to have this I wont implement this. Most of the time you will want to know specific information about an object. Having a ToString listing all 20+ properties for an object isn't that helpful in most situations.

**Comment by Surfang** [comment]
Hi!
OrderType have type OrderSideExtended. How convert to string?

**Comment by JKorf** [comment]
Why do you want to convert it to string?

**Comment by Surfang** [comment]
For comparison

**Comment by JKorf** [comment]
Comparison of what? Why wouldn't you be able to use the enum?

**Comment by Surfang** [comment]
enum OperationType
    {
        TypeSell,
        TypeBay
    }
            for (int i = 0; i < openOrders.Data.Length; i++)
            {
               if (openOrders.Data[i].OrderType == OperationType.TypeBay)
            }
not work

**Comment by JKorf** [comment]
I don't think a ToString() would help.
Can't you just do this to check if it is a buy?:
````C#
for (int i = 0; i < openOrders.Data.Length; i++)
            {
                if (openOrders.Data[i].OrderType == OrderSideExtended.LimitBuy || openOrders.Data[i].OrderType == OrderSideExtended.MarketBuy)
                  {
                        // Buy order
                  }
                  else {
                          // Sell order
                  }
            }
````

**Comment by Surfang** [comment]
Just the last time I wrote in C++15 years ago. Thank You
