### ISSUE TITLE
Error setting value to 'Side' on 'Bittrex.Net.Objects.BittrexOrderResult'

### ISSUE THREAD

**Issue by sergey-prokhorov** [JKorf/Bittrex.Net#98]
method PlaceConditionalOrder()

Error deserializing data: Deserialize JsonSerializationException: Error setting value to 'Side' on 'Bittrex.Net.Objects.BittrexOrderResult'.. Received data: {"success":true,"message":"","result":{"OrderId":"995bc31b-1949-434c-86b1-45eadb60d8c3","MarketName":"BTC-SC","MarketCurrency":"SC","BuyOrSell":"Sell","OrderType":"Limit","Quantity":708.0,"Rate":0.0000026}}

please help me!
all packages is up to date.
seems like [JsonConverter(typeof(OrderSideConverter)), JsonProperty("BuyOrSell")]
not working properly.

upd: the problem is in the new version CryptoExchange.Net

**Comment by sauropodlet** [comment]
I can confirm that the latest CryptoExchange.Net breaks the latest Bittrex.Net, although my problem was in BittrexSocketClient.SubscribeToOrderUpdates

**Comment by pwnzya** [comment]
Hello.

In the past, I've also made the [assumption](#79) that I should be able to use the latest version of Bittrex.Net together with the latest version of CryptoExchange.Net, and it was not the case.

The Bittrex.Net package needs a corresponding CryptoExchange.Net package.
The latest Bittrex.Net version 2.1.2 is based on CryptoExchange.Net version 0.0.19.

**Comment by JKorf** [comment]
As @pwnzya stated, newer version of CryptoExchange.Net aren't necessarily compatible with the latest Bittrex.Net. 
I've just pushed a new version which of Bittrex.Net (v2.1.3) and CryptoExchange.Net (v0.0.24) which should work for you.
